# -*- coding: utf-8 -*-
"""softwaremodule_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dqfOb3c-8imP0dQi7htFYokHHPFK6pa1
"""

import numpy as np
import matplotlib.pyplot as plt

# module2_ex1_gate_fidelity.py

# ---------- Linear algebra helpers ----------
def dagger(A):  # conjugate transpose
    return np.conjugate(A.T)

def eigh_sqrt(A):
    """Matrix square root for (nearly) PSD Hermitian A."""
    A = 0.5 * (A + dagger(A))              # symmetrize numerically
    w, V = np.linalg.eigh(A)
    w = np.clip(w, 0.0, None)
    return (V * np.sqrt(w)) @ dagger(V)

def density_from_state(psi):
    psi = psi.reshape(-1, 1)
    return psi @ dagger(psi)

# ---------- Test-state set: d basis states + equal superposition ----------
def test_state_set(n_qubits: int):
    d = 2 ** n_qubits
    basis = []
    for i in range(d):
        ket = np.zeros((d, 1), dtype=complex)
        ket[i, 0] = 1.0
        basis.append(ket @ dagger(ket))
    vec = np.ones((d, 1), dtype=complex) / np.sqrt(d)
    TR = vec @ dagger(vec)                 # |+...+><+...+|
    return basis, TR

# ---------- Uhlmann state fidelity ----------
def state_fidelity(rho, sigma):
    # Fast path when both are pure: F = Tr(rho sigma)
    tr_r2 = np.real_if_close(np.trace(rho @ rho))
    tr_s2 = np.real_if_close(np.trace(sigma @ sigma))
    if abs(tr_r2 - 1.0) < 1e-10 and abs(tr_s2 - 1.0) < 1e-10:
        val = np.real_if_close(np.trace(rho @ sigma))
        return float(np.clip(val, 0.0, 1.0))

    A = eigh_sqrt(rho) @ sigma @ eigh_sqrt(rho)
    F_root = np.real_if_close(np.trace(eigh_sqrt(A)))
    F = float(np.clip(F_root, 0.0, None)) ** 2
    return float(np.clip(F, 0.0, 1.0))

def evolve_unitary(U, rho):
    return U @ rho @ dagger(U)

# ---------- Gate fidelities from states (eqs. 5–8) ----------
def gate_fidelities_states(U_target, U_impl, n_qubits=1):
    """Returns Farith, Fgeom, Flambda, per-state list."""
    basis, TR = test_state_set(n_qubits)
    d = 2 ** n_qubits

    F_list = []
    for rho_in in basis + [TR]:
        rho_t = evolve_unitary(U_target, rho_in)
        rho_i = evolve_unitary(U_impl,  rho_in)
        F_list.append(state_fidelity(rho_t, rho_i))

    Farith = float(np.mean(F_list))                          # arithmetic mean
    Fgeom  = float(np.prod(F_list)) ** (1.0 / (d + 1))       # geometric mean

    FB, FTR = F_list[:-1], F_list[-1]                        # basis vs TR term
    prod_basis = float(np.prod(FB))
    eps = 1e-16
    lam = 1.0 - (1.0 - prod_basis) / (1.0 - prod_basis * FTR + eps)  # eq. (8)
    Flambda = lam * Fgeom + (1.0 - lam) * Farith             # eq. (7)

    return Farith, Fgeom, Flambda, F_list

# ---------- Operator-level average gate fidelity for unitaries ----------
def avg_gate_fidelity_unitary(U_target, U_impl):
    d = U_target.shape[0]
    chi = np.trace(dagger(U_target) @ U_impl)
    return (abs(chi) ** 2 + d) / (d * (d + 1))

# ---------- Single-qubit gates ----------
I2 = np.eye(2, dtype=complex)
X  = np.array([[0, 1], [1, 0]], dtype=complex)
Y  = np.array([[0, -1j], [1j, 0]], dtype=complex)
Z  = np.array([[1, 0], [0, -1]], dtype=complex)

def Rx(theta):
    # Rx(theta) = cos(theta/2) I - i sin(theta/2) X
    return np.cos(theta/2.0) * I2 - 1j * np.sin(theta/2.0) * X

# ---------- Pretty print helpers ----------
def print_row(cols, widths):
    line = "  ".join(str(c).ljust(w) for c, w in zip(cols, widths))
    print(line)

def print_table(rows, headers):
    widths = [max(len(h), *(len(str(r[i])) for r in rows)) for i, h in enumerate(headers)]
    print_row(headers, widths)
    print_row(["-" * w for w in widths], widths)
    for r in rows: print_row(r, widths)

# ---------- Exercise 1(a): X vs {X, Y, Z, I} ----------
def ex1a():
    others = {"X (itself)": X, "Y": Y, "Z": Z, "I": I2}
    rows = []
    for name, Uo in others.items():
        Farith, Fgeom, Flambda, _ = gate_fidelities_states(X, Uo, 1)
        Favg = avg_gate_fidelity_unitary(X, Uo)
        rows.append([
            name,
            f"{Farith:.6f}",
            f"{Fgeom:.6f}",
            f"{Flambda:.6f}",
            f"{Favg:.6f}",
        ])
    print("\nExercise 1(a): Target X vs {X,Y,Z,I}\n")
    print_table(rows, headers=["Implementation", "Farith", "Fgeom", "Flambda", "Favg(op)"])

# ---------- Exercise 1(b): X vs Rx(theta) sweep ----------
def ex1b():
    thetas = np.linspace(0, 2*np.pi, 301)
    f_ar, f_g, f_l, f_avg = [], [], [], []
    for th in thetas:
        Farith, Fgeom, Flambda, _ = gate_fidelities_states(X, Rx(th), 1)
        f_ar.append(Farith); f_g.append(Fgeom); f_l.append(Flambda)
        f_avg.append(avg_gate_fidelity_unitary(X, Rx(th)))

    plt.figure(figsize=(7, 4.5))
    plt.plot(thetas, f_ar,  label="Farith (states)")
    plt.plot(thetas, f_g,   label="Fgeom (states)")
    plt.plot(thetas, f_l,   label="Flambda (states)")
    plt.plot(thetas, f_avg, linestyle="--", label="Favg (operator)")
    plt.xlabel(r"$\theta$ (radians)"); plt.ylabel("Fidelity")
    plt.title("X vs Rx(θ): Gate Fidelity (Module 2, Ex. 1)")
    plt.legend(); plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()

# ---------- Exercise 1(c): random unitary trials ----------
def random_unitary(d, rng):
    Z = (rng.normal(size=(d, d)) + 1j * rng.normal(size=(d, d))) / np.sqrt(2.0)
    Q, R = np.linalg.qr(Z)
    D = np.diag(np.exp(1j * np.angle(np.diag(R))))  # fix phases
    return Q @ dagger(D)

def ex1c():
    rng = np.random.default_rng(7)
    rows, diffs = [], []
    for k in range(5):
        Uo = random_unitary(2, rng)
        Farith, Fgeom, Flambda, _ = gate_fidelities_states(X, Uo, 1)
        Favg = avg_gate_fidelity_unitary(X, Uo)
        rows.append([k+1, f"{Farith:.6f}", f"{Fgeom:.6f}", f"{Flambda:.6f}", f"{Favg:.6f}"])
        diffs.append(Flambda - Favg)

    print("\nExercise 1(c): Random unitary tests (target X)\n")
    print_table(rows, headers=["Trial", "Farith", "Fgeom", "Flambda", "Favg(op)"])

    plt.figure(figsize=(6, 4))
    plt.plot(range(1, len(diffs)+1), diffs, marker="o")
    plt.axhline(0.0, linestyle="--")
    plt.xlabel("Random trial"); plt.ylabel("Flambda - Favg(op)")
    plt.title("Mixed (states) vs Operator Average Fidelity")
    plt.grid(True, alpha=0.3); plt.tight_layout()
    plt.show()

# ---------- Main ----------
if __name__ == "__main__":
    ex1a()
    ex1b()
    ex1c()

# module2_ex2_ex3.py — fixed dtype for np.eye

import numpy as np
import matplotlib.pyplot as plt

try:
    from scipy.optimize import minimize
    SCIPY_OK = True
except Exception:
    SCIPY_OK = False

def dagger(A): return np.conjugate(A.T)

def eigh_sqrt(A):
    A = 0.5*(A + dagger(A))
    w, V = np.linalg.eigh(A)
    w = np.clip(w, 0.0, None)
    return (V * np.sqrt(w)) @ dagger(V)

def density_from_state(psi):
    psi = psi.reshape(-1,1)
    return psi @ dagger(psi)

def test_state_set(n_qubits: int):
    d = 2**n_qubits
    basis = []
    for i in range(d):
        ket = np.zeros((d,1), complex); ket[i,0] = 1.0
        basis.append(ket @ dagger(ket))
    vec = np.ones((d,1), complex)/np.sqrt(d)
    TR = vec @ dagger(vec)
    return basis, TR

def state_fidelity(rho, sigma):
    tr_r2 = np.real_if_close(np.trace(rho @ rho))
    tr_s2 = np.real_if_close(np.trace(sigma @ sigma))
    if abs(tr_r2-1.0) < 1e-10 and abs(tr_s2-1.0) < 1e-10:
        val = np.real_if_close(np.trace(rho @ sigma))
        return float(np.clip(val, 0.0, 1.0))
    A = eigh_sqrt(rho) @ sigma @ eigh_sqrt(rho)
    F_root = np.real_if_close(np.trace(eigh_sqrt(A)))
    F = float(np.clip(F_root, 0.0, None))**2
    return float(np.clip(F, 0.0, 1.0))

def evolve_unitary(U, rho): return U @ rho @ dagger(U)

def gate_fidelities_states(U_target, U_impl, n_qubits):
    basis, TR = test_state_set(n_qubits)
    d = 2**n_qubits
    F_list = []
    for rho_in in basis + [TR]:
        rho_t = evolve_unitary(U_target, rho_in)
        rho_i = evolve_unitary(U_impl,  rho_in)
        F_list.append(state_fidelity(rho_t, rho_i))
    Farith = float(np.mean(F_list))
    Fgeom  = float(np.prod(F_list)) ** (1.0/(d+1))
    FB, FTR = F_list[:-1], F_list[-1]
    prod_basis = float(np.prod(FB))
    eps = 1e-16
    lam = 1.0 - (1.0 - prod_basis)/(1.0 - prod_basis*FTR + eps)
    Flambda = lam*Fgeom + (1.0 - lam)*Farith
    return Farith, Fgeom, Flambda, F_list

def avg_gate_fidelity_unitary(U_target, U_impl):
    d = U_target.shape[0]
    chi = np.trace(dagger(U_target) @ U_impl)
    return (abs(chi)**2 + d) / (d*(d+1))

# ---- 1-qubit gates (FIXED dtype=complex) ----
I2 = np.eye(2, dtype=complex)
X  = np.array([[0,1],[1,0]], dtype=complex)
Y  = np.array([[0,-1j],[1j,0]], dtype=complex)
Z  = np.array([[1,0],[0,-1]], dtype=complex)

def Rx(theta): return np.cos(theta/2)*I2 - 1j*np.sin(theta/2)*X
def Rz(phi):
    h = phi/2
    return np.array([[np.exp(-1j*h), 0.0],[0.0, np.exp(1j*h)]], dtype=complex)

def ZXZ(a,b,c): return Rz(a) @ Rx(b) @ Rz(c)

# ---- 2-qubit helpers ----
def kron(*ops):
    out = np.array([[1.0+0j]])
    for op in ops:
        out = np.kron(out, op)
    return out

def twoq_ZXZ(a1,b1,c1,a2,b2,c2):
    return kron(ZXZ(a1,b1,c1), ZXZ(a2,b2,c2))

def random_unitary(d, rng=None):
    rng = np.random.default_rng() if rng is None else rng
    Zm = (rng.normal(size=(d,d)) + 1j*rng.normal(size=(d,d))) / np.sqrt(2.0)
    Q, R = np.linalg.qr(Zm)
    D = np.diag(np.exp(1j*np.angle(np.diag(R))))
    return Q @ dagger(D)

def _print_table(rows, headers):
    widths = [max(len(h), *(len(str(r[i])) for r in rows)) for i,h in enumerate(headers)]
    def line(cols): print("  ".join(str(c).ljust(w) for c,w in zip(cols, widths)))
    line(headers); line(["-"*w for w in widths])
    for r in rows: line(r)

# ================= Exercise 2 =================
def exercise2_optimize_zxz():
    print("\n=== Exercise 2: Optimize ZXZ (single qubit) ===")
    rng = np.random.default_rng(3)
    U_target = random_unitary(2, rng)
    def obj(p):
        a,b,c = p
        U_impl = ZXZ(a,b,c)
        _,_,Fl,_ = gate_fidelities_states(U_target, U_impl, 1)
        return -Fl
    if not SCIPY_OK:
        print("SciPy not found; skipping minimize()."); return
    methods = ["Nelder-Mead", "Powell", "L-BFGS-B"]
    history = {m: [] for m in methods}
    for m in methods:
        trace = []
        def cb(xk): trace.append(-obj(xk))
        res = minimize(obj, np.array([0.1,0.7,-0.4]), method=m,
                       callback=cb, options={"maxiter":400, "disp":False})
        best = -res.fun
        history[m].extend(trace)
        print(f"{m:12s}: best Flambda = {best:.12f}, iters={len(trace)}")
    plt.figure(figsize=(6,4))
    for m in methods:
        if history[m]: plt.plot(range(1,len(history[m])+1), history[m], label=m)
    plt.xlabel("Iteration"); plt.ylabel("Fidelity (Flambda)")
    plt.title("Exercise 2: ZXZ optimization convergence")
    plt.legend(); plt.grid(True, alpha=0.3); plt.tight_layout(); plt.show()

# ================= Exercise 3 =================
def exercise3_two_qubit():
    print("\n=== Exercise 3: Two-qubit gates ===")
    XX = kron(X,X); XY = kron(X,Y); IZ = kron(I2,Z); II = kron(I2,I2)
    paulis = {"XX":XX, "XY":XY, "IZ":IZ, "II":II}

    print("\n(a) Target XX vs {XX, XY, IZ, II}")
    rows = []
    for name,Uo in paulis.items():
        Far,Fg,Fl,_ = gate_fidelities_states(XX, Uo, 2)
        Fav = avg_gate_fidelity_unitary(XX, Uo)
        rows.append([name, f"{Far:.6f}", f"{Fg:.6f}", f"{Fl:.6f}", f"{Fav:.6f}"])
    _print_table(rows, headers=["Impl","Farith","Fgeom","Flambda","Favg(op)"])

    print("\n(b) Heatmap: U_impl = Rx(t1) ⊗ Rx(t2) vs XX")
    thetas = np.linspace(0, 2*np.pi, 121)
    heat = np.zeros((len(thetas), len(thetas)))
    for i,t1 in enumerate(thetas):
        for j,t2 in enumerate(thetas):
            U_impl = kron(Rx(t1), Rx(t2))
            _,_,Fl,_ = gate_fidelities_states(XX, U_impl, 2)
            heat[i,j] = Fl
    plt.figure(figsize=(6,5))
    im = plt.imshow(heat, origin="lower", extent=[0,2*np.pi,0,2*np.pi], aspect="auto")
    plt.colorbar(im, label="Flambda")
    plt.xlabel(r"$\theta_2$"); plt.ylabel(r"$\theta_1$")
    plt.title("Exercise 3(b): Flambda for Rx⊗Rx vs XX")
    plt.tight_layout(); plt.show()

    rng = np.random.default_rng(5)
    U_rand2 = random_unitary(4, rng)
    print("\n(c) Random 2-qubit target vs Rx⊗Rx heatmap")
    heat2 = np.zeros_like(heat)
    for i,t1 in enumerate(thetas):
        for j,t2 in enumerate(thetas):
            U_impl = kron(Rx(t1), Rx(t2))
            _,_,Fl,_ = gate_fidelities_states(U_rand2, U_impl, 2)
            heat2[i,j] = Fl
    plt.figure(figsize=(6,5))
    im = plt.imshow(heat2, origin="lower", extent=[0,2*np.pi,0,2*np.pi], aspect="auto")
    plt.colorbar(im, label="Flambda")
    plt.xlabel(r"$\theta_2$"); plt.ylabel(r"$\theta_1$")
    plt.title("Exercise 3(c): Flambda for Rx⊗Rx vs random target")
    plt.tight_layout(); plt.show()

    if SCIPY_OK:
        print("\n(d) 6-param local optimization (Nelder–Mead)")
        def obj6(p, U_t):
            a1,b1,c1,a2,b2,c2 = p
            U_impl = twoq_ZXZ(a1,b1,c1,a2,b2,c2)
            _,_,Fl,_ = gate_fidelities_states(U_t, U_impl, 2)
            return -Fl
        for tag, U_t in [("target XX (product)", XX), ("random 2-qubit (entangling)", U_rand2)]:
            x0 = np.array([0.1,0.5,-0.3, 0.2,-0.7,0.4])
            trace = []
            def cb(xk): trace.append(-obj6(xk, U_t))
            res = minimize(obj6, x0, args=(U_t,), method="Nelder-Mead",
                           callback=cb, options={"maxiter":800, "disp":False})
            best = -res.fun
            print(f"  {tag:32s} -> best Flambda = {best:.12f}, iters={len(trace)}")
            if trace:
                plt.figure(figsize=(6,4))
                plt.plot(range(1,len(trace)+1), trace, label=tag)
                plt.xlabel("Iteration"); plt.ylabel("Fidelity (Flambda)")
                plt.title("Exercise 3(d): local optimization")
                plt.grid(True, alpha=0.3); plt.legend(); plt.tight_layout(); plt.show()
    else:
        print("\n(d) SciPy not found; skipping 6-param optimization.")

if __name__ == "__main__":
    exercise2_optimize_zxz()
    exercise3_two_qubit()

# module3_single_atom_x_gate.py
# Neutral Atom Gates — Single Atom — Exercise 1 (X gate)
# NumPy-only Lindblad simulator + Gaussian pulse + fidelity vs ideal X.

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401  (needed for 3D)

# -------------------- Units & helpers --------------------
TWOPI = 2.0 * np.pi
def w(MHz):  # frequency (MHz) -> angular freq (rad / microsecond)
    return TWOPI * MHz

def dagger(A): return np.conjugate(A.T)

def op(i, j, d=4):
    """|i><j| in dimension d."""
    M = np.zeros((d, d), dtype=complex); M[i, j] = 1.0
    return M

def eigh_sqrt_psd(A):
    A = 0.5 * (A + dagger(A))
    wv, V = np.linalg.eigh(A)
    wv = np.clip(wv, 0.0, None)
    return (V * np.sqrt(wv)) @ dagger(V)

# Uhlmann state fidelity
def state_fidelity(rho, sigma):
    tr_r2 = np.real_if_close(np.trace(rho @ rho))
    tr_s2 = np.real_if_close(np.trace(sigma @ sigma))
    if abs(tr_r2 - 1.0) < 1e-10 and abs(tr_s2 - 1.0) < 1e-10:
        val = np.real_if_close(np.trace(rho @ sigma))
        return float(np.clip(val, 0.0, 1.0))
    A = eigh_sqrt_psd(rho) @ sigma @ eigh_sqrt_psd(rho)
    Froot = np.real_if_close(np.trace(eigh_sqrt_psd(A)))
    F = float(np.clip(Froot, 0.0, None))**2
    return float(np.clip(F, 0.0, 1.0))

# -------------------- 4-level atom model --------------------
# Basis ordering: |0>, |1>, |r>, |d>
ket0, ket1, ketr, ketd = [op(i,0)[:,0] for i in range(4)]

# Hamiltonian pieces
X01 = op(0,1) + op(1,0)  # |0><1| + |1><0|
# (No Rydberg drive here; Delta_r=0, Omega_r=0; delta_1=0)

def H_of_t_Omega01(Omega0_MHz, t0_us, sigma_us):
    """Return a function H(t) implementing (Ω01(t)/2) X01."""
    Omega0 = w(Omega0_MHz)  # rad / us
    def H(t_us):
        Omega_t = Omega0 * np.exp(-((t_us - t0_us)**2) / (2.0 * sigma_us**2))
        return 0.5 * Omega_t * X01  # H = (Ω/2) σ_x
    return H

# Lindblad jump operators: r -> {0,1,d} with branching
def lindblad_jumps(gamma_r_per_us, b0=1/16, b1=1/16, bd=7/8):
    L0 = np.sqrt(gamma_r_per_us * b0) * op(0,2)  # |0><r|
    L1 = np.sqrt(gamma_r_per_us * b1) * op(1,2)  # |1><r|
    Ld = np.sqrt(gamma_r_per_us * bd) * op(3,2)  # |d><r|
    return [L0, L1, Ld]

# -------------------- Lindblad RK4 integrator --------------------
def lindblad_rhs(rho, t_us, H_of_t, Ls):
    Ht = H_of_t(t_us)
    comm = -1j * (Ht @ rho - rho @ Ht)
    diss = np.zeros_like(rho, dtype=complex)
    for L in Ls:
        Ld = dagger(L)
        diss += L @ rho @ Ld - 0.5 * (Ld @ L @ rho + rho @ Ld @ L)
    return comm + diss

def evolve_rho(tspan_us, rho0, H_of_t, Ls, steps=4000):
    t0, t1 = float(tspan_us[0]), float(tspan_us[1])
    ts = np.linspace(t0, t1, steps + 1)
    dt = (t1 - t0) / steps
    rho = rho0.astype(complex)
    traj = [rho.copy()]
    for k in range(steps):
        t = ts[k]
        k1 = lindblad_rhs(rho, t, H_of_t, Ls)
        k2 = lindblad_rhs(rho + 0.5*dt*k1, t + 0.5*dt, H_of_t, Ls)
        k3 = lindblad_rhs(rho + 0.5*dt*k2, t + 0.5*dt, H_of_t, Ls)
        k4 = lindblad_rhs(rho + dt*k3,     t + dt,     H_of_t, Ls)
        rho = rho + (dt/6.0)*(k1 + 2*k2 + 2*k3 + k4)
        # Enforce Hermiticity + trace ≈ 1 (tiny numeric cleaning)
        rho = 0.5*(rho + dagger(rho))
        traj.append(rho.copy())
    return ts, np.array(traj)

# -------------------- Gate fidelity on 2x2 subspace --------------------
I2 = np.eye(2, dtype=complex)
X = np.array([[0,1],[1,0]], dtype=complex)

def test_state_set_1q():
    # basis + |+><+|
    basis = [np.array([[1,0],[0,0]], complex),
             np.array([[0,0],[0,1]], complex)]
    plus = np.array([[0.5,0.5],[0.5,0.5]], complex)
    return basis, plus

def gate_fidelities_states_1q(U_target, pulse_evolve_fn):
    """
    pulse_evolve_fn(ρ2x2)->ρ2x2: embeds 2x2 into 4x4, evolves full system,
    returns the 2x2 computational block at the final time (no renorm).
    """
    basis, TR = test_state_set_1q()
    F_list = []
    for rho_in in basis + [TR]:
        # Ideal target output in 2x2
        rho_t = U_target @ rho_in @ dagger(U_target)
        # Actual output via pulse
        rho_i = pulse_evolve_fn(rho_in)
        F_list.append(state_fidelity(rho_t, rho_i))
    Farith = float(np.mean(F_list))
    Fgeom  = float(np.prod(F_list)) ** (1/3)
    FB, FTR = F_list[:-1], F_list[-1]
    prod_basis = float(np.prod(FB))
    eps = 1e-16
    lam = 1.0 - (1.0 - prod_basis)/(1.0 - prod_basis*FTR + eps)
    Flambda = lam*Fgeom + (1.0 - lam)*Farith
    return Farith, Fgeom, Flambda, F_list

# -------------------- Convenience wrappers for this exercise --------------------
def embed_2x2_to_4x4(rho2):
    rho4 = np.zeros((4,4), complex)
    rho4[:2,:2] = rho2
    return rho4

def extract_2x2_from_4x4(rho4):
    return rho4[:2,:2]

def simulate_pulse_return_2x2(Omega0_MHz, sigma_us, t0_us=0.0,
                              gamma_r_inv_us=540.0, steps=4000):
    """
    Returns (ts, traj0, traj1, pulse_fn, H_of_t, Ls)
    where trajX are 4x4 trajectories for initial |X>, X in {0,1}.
    """
    gamma_r = 1.0 / gamma_r_inv_us  # per microsecond
    Ht = H_of_t_Omega01(Omega0_MHz, t0_us, sigma_us)
    Ls = lindblad_jumps(gamma_r, b0=1/16, b1=1/16, bd=7/8)

    # choose window wide enough (±6σ)
    tspan = (t0_us - 6.0*sigma_us, t0_us + 6.0*sigma_us)

    rho0 = embed_2x2_to_4x4(np.array([[1,0],[0,0]], complex))
    rho1 = embed_2x2_to_4x4(np.array([[0,0],[0,1]], complex))

    ts, traj0 = evolve_rho(tspan, rho0, Ht, Ls, steps=steps)
    _,  traj1 = evolve_rho(tspan, rho1, Ht, Ls, steps=steps)

    def pulse_evolve_fn(rho2x2):
        rho4 = embed_2x2_to_4x4(rho2x2)
        _, tr = evolve_rho(tspan, rho4, Ht, Ls, steps=steps)
        return extract_2x2_from_4x4(tr[-1])

    return ts, traj0, traj1, pulse_evolve_fn, Ht, Ls

def pop1_from_traj(traj4):
    """Population of |1> from 4x4 trajectory."""
    return np.real_if_close(traj4[:,1,1])

# -------------------- Plots required by the exercise --------------------
def plot_p1_vs_time_fixed_sigma():
    sig = 1.0  # microseconds
    Omegas = [0.0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5]  # MHz
    plt.figure(figsize=(7,4.5))
    for Om in Omegas:
        ts, traj0, _, _, _, _ = simulate_pulse_return_2x2(Om, sig)
        plt.plot(ts, pop1_from_traj(traj0), label=f"Ω0={Om} MHz")
    plt.xlabel("time (µs)"); plt.ylabel("P(|1⟩)")
    plt.title("Fixed σ=1 µs: population of |1⟩ vs time")
    plt.legend(); plt.grid(True, alpha=0.3); plt.tight_layout(); plt.show()

def plot_p1_vs_time_fixed_omega():
    Om = 1.0  # MHz
    sigmas = [0.5, 1, 1.5, 2, 4, 8]  # µs
    plt.figure(figsize=(7,4.5))
    for sig in sigmas:
        ts, traj0, _, _, _, _ = simulate_pulse_return_2x2(Om, sig)
        plt.plot(ts, pop1_from_traj(traj0), label=f"σ={sig} µs")
    plt.xlabel("time (µs)"); plt.ylabel("P(|1⟩)")
    plt.title("Fixed Ω0=1 MHz: population of |1⟩ vs time")
    plt.legend(); plt.grid(True, alpha=0.3); plt.tight_layout(); plt.show()

# π-pulse width from Gaussian area
def sigma_pi_for(Omega0_MHz):
    Omega0_rad = w(Omega0_MHz)  # rad/us
    return np.pi / (Omega0_rad * np.sqrt(2.0*np.pi))

def run_pi_pulse_and_fidelity(Omega0_MHz=1.0):
    sig_opt = sigma_pi_for(Omega0_MHz)
    ts, traj0, traj1, pulse_fn, *_ = simulate_pulse_return_2x2(Omega0_MHz, sig_opt)

    # Show that |0>→|1>, |1>→|0>
    plt.figure(figsize=(7,4.5))
    plt.plot(ts, pop1_from_traj(traj0), label="init |0⟩ → P(|1⟩)")
    plt.plot(ts, 1 - pop1_from_traj(traj1), label="init |1⟩ → 1-P(|1⟩)")
    plt.xlabel("time (µs)"); plt.ylabel("population")
    plt.title(f"π pulse (Ω0={Omega0_MHz} MHz, σ≈{sig_opt:.3f} µs)")
    plt.legend(); plt.grid(True, alpha=0.3); plt.tight_layout(); plt.show()

    # Gate fidelity vs ideal X on 2x2 subspace
    Far, Fg, Fl, _ = gate_fidelities_states_1q(X, pulse_fn)
    print(f"Gate fidelity vs ideal X  (Ω0={Omega0_MHz} MHz, σ≈{sig_opt:.6f} µs)")
    print(f"  Farith  = {Far:.12f}")
    print(f"  Fgeom   = {Fg:.12f}")
    print(f"  Flambda = {Fl:.12f}")

    return sig_opt

# Optional: brute optimize σ by scanning (no SciPy dependency)
def find_sigma_by_scan(Omega0_MHz=1.0, smin=0.1, smax=8.0, N=60):
    sigmas = np.linspace(smin, smax, N)
    best = (-1.0, None)
    for sig in sigmas:
        _, _, _, pulse_fn, *_ = simulate_pulse_return_2x2(Omega0_MHz, sig, steps=2000)
        _, _, Fl, _ = gate_fidelities_states_1q(X, pulse_fn)
        if Fl > best[0]: best = (Fl, sig)
    print(f"[scan] best Flambda={best[0]:.12f} at σ≈{best[1]:.6f} µs")
    return best

# Bloch trajectory for optimal parameters
def plot_bloch_trajectory(Omega0_MHz=1.0):
    sig_opt = sigma_pi_for(Omega0_MHz)
    ts, traj0, traj1, *_ = simulate_pulse_return_2x2(Omega0_MHz, sig_opt)
    # Extract 2x2 blocks and Bloch vectors
    rho0 = np.array([extract_2x2_from_4x4(r) for r in traj0])
    rho1 = np.array([extract_2x2_from_4x4(r) for r in traj1])

    def bloch_coords(r):
        x = 2*np.real(r[:,0,1])
        y = -2*np.imag(r[:,0,1])
        z = np.real(r[:,0,0] - r[:,1,1])
        return x, y, z

    x0,y0,z0 = bloch_coords(rho0)
    x1,y1,z1 = bloch_coords(rho1)

    fig = plt.figure(figsize=(6,6))
    ax = fig.add_subplot(111, projection='3d')
    # Draw wireframe sphere
    u = np.linspace(0, 2*np.pi, 60)
    v = np.linspace(0, np.pi, 30)
    xs = np.outer(np.cos(u), np.sin(v))
    ys = np.outer(np.sin(u), np.sin(v))
    zs = np.outer(np.ones_like(u), np.cos(v))
    ax.plot_wireframe(xs, ys, zs, linewidth=0.2, alpha=0.3)
    # Trajectories
    ax.plot(x0, y0, z0, label="init |0⟩")
    ax.plot(x1, y1, z1, label="init |1⟩")
    ax.set_xlabel("x"); ax.set_ylabel("y"); ax.set_zlabel("z")
    ax.set_title(f"Bloch trajectories (Ω0={Omega0_MHz} MHz, σ≈{sig_opt:.3f} µs)")
    ax.legend()
    plt.tight_layout(); plt.show()

# -------------------- Run all parts --------------------
if __name__ == "__main__":
    # 1) P1(t) vs time for fixed sigma and varying Omega0
    plot_p1_vs_time_fixed_sigma()

    # 2) P1(t) vs time for fixed Omega0 and varying sigma
    plot_p1_vs_time_fixed_omega()

    # 3) π pulse + fidelity vs ideal X
    sigma_opt = run_pi_pulse_and_fidelity(Omega0_MHz=1.0)

    # 4) Optional: numeric sweep to compare with analytic sigma
    find_sigma_by_scan(Omega0_MHz=1.0, smin=0.2, smax=3.0, N=40)
    print(f"Analytic σ_pi ≈ {sigma_opt:.6f} µs")

    # 5) Bloch-sphere trajectories for optimal params
    plot_bloch_trajectory(Omega0_MHz=1.0)

# module3_single_atom_z_gate.py
# Neutral Atom Gates — Single Atom — Exercise 2 (Z gate)
# Constant detuning δ1(t) on |1> for duration T; RK4 Lindblad; fidelity vs ideal Z.

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401

# --- optional SciPy for 1D optimization over T ---
try:
    from scipy.optimize import minimize
    SCIPY_OK = True
except Exception:
    SCIPY_OK = False

# =================== Utilities & physics helpers ===================
TWOPI = 2*np.pi
def w(MHz):      # MHz -> rad / microsecond
    return TWOPI * MHz

def dagger(A): return np.conjugate(A.T)

def op(i, j, d=4):
    M = np.zeros((d, d), dtype=complex); M[i, j] = 1.0
    return M

def eigh_sqrt_psd(A):
    A = 0.5*(A + dagger(A))
    wv, V = np.linalg.eigh(A)
    wv = np.clip(wv, 0.0, None)
    return (V * np.sqrt(wv)) @ dagger(V)

def state_fidelity(rho, sigma):
    tr_r2 = np.real_if_close(np.trace(rho @ rho))
    tr_s2 = np.real_if_close(np.trace(sigma @ sigma))
    if abs(tr_r2-1.0) < 1e-10 and abs(tr_s2-1.0) < 1e-10:
        val = np.real_if_close(np.trace(rho @ sigma))
        return float(np.clip(val, 0.0, 1.0))
    A = eigh_sqrt_psd(rho) @ sigma @ eigh_sqrt_psd(rho)
    Froot = np.real_if_close(np.trace(eigh_sqrt_psd(A)))
    F = float(np.clip(Froot, 0.0, None))**2
    return float(np.clip(F, 0.0, 1.0))

# =================== 4-level atom model ===================
# Basis: |0>, |1>, |r>, |d|
Z01_4 = op(0,0) - op(1,1)  # embeds σz on {0,1} into 4x4

def H_detuning_of_t(delta_MHz, T_det_us):
    """H(t) = (δ/2) Z01 for 0<=t<T_det, else 0."""
    delta = w(delta_MHz)  # rad/us
    def H(t_us):
        if 0.0 <= t_us < T_det_us:
            return 0.5 * delta * Z01_4
        else:
            return np.zeros((4,4), dtype=complex)
    return H

def lindblad_jumps(gamma_r_per_us, b0=1/16, b1=1/16, bd=7/8):
    # r -> {0,1,d}; will be inactive here because we never populate |r>
    L0 = np.sqrt(gamma_r_per_us * b0) * op(0,2)
    L1 = np.sqrt(gamma_r_per_us * b1) * op(1,2)
    Ld = np.sqrt(gamma_r_per_us * bd) * op(3,2)
    return [L0, L1, Ld]

def lindblad_rhs(rho, t_us, H_of_t, Ls):
    Ht = H_of_t(t_us)
    comm = -1j * (Ht @ rho - rho @ Ht)
    diss = np.zeros_like(rho, dtype=complex)
    for L in Ls:
        Ld = dagger(L)
        diss += L @ rho @ Ld - 0.5*(Ld @ L @ rho + rho @ Ld @ L)
    return comm + diss

def evolve_rho(t0, t1, rho0, H_of_t, Ls, steps=4000):
    ts = np.linspace(t0, t1, steps+1)
    dt = (t1 - t0)/steps
    rho = rho0.astype(complex)
    traj = [rho.copy()]
    for k in range(steps):
        t = ts[k]
        k1 = lindblad_rhs(rho, t, H_of_t, Ls)
        k2 = lindblad_rhs(rho + 0.5*dt*k1, t + 0.5*dt, H_of_t, Ls)
        k3 = lindblad_rhs(rho + 0.5*dt*k2, t + 0.5*dt, H_of_t, Ls)
        k4 = lindblad_rhs(rho + dt*k3,     t + dt,     H_of_t, Ls)
        rho = rho + (dt/6.0)*(k1 + 2*k2 + 2*k3 + k4)
        rho = 0.5*(rho + dagger(rho))
        traj.append(rho.copy())
    return ts, np.array(traj)

# =================== Subspace plumbing & fidelity ===================
I2 = np.eye(2, dtype=complex)
Z2 = np.array([[1,0],[0,-1]], dtype=complex)

def embed_2x2_to_4x4(r2):
    r4 = np.zeros((4,4), complex)
    r4[:2,:2] = r2
    return r4

def extract_2x2_from_4x4(r4):
    return r4[:2,:2]

def test_state_set_1q():
    basis = [np.array([[1,0],[0,0]], complex),
             np.array([[0,0],[0,1]], complex)]
    plus = np.array([[0.5,0.5],[0.5,0.5]], complex)
    return basis, plus

def gate_fids_states_1q(U_target, evolve2x2_fn):
    basis, TR = test_state_set_1q()
    Flist = []
    for rho_in in basis + [TR]:
        rho_t = U_target @ rho_in @ dagger(U_target)
        rho_i = evolve2x2_fn(rho_in)
        Flist.append(state_fidelity(rho_t, rho_i))
    Far = float(np.mean(Flist))
    Fg  = float(np.prod(Flist)) ** (1/3)
    FB, FTR = Flist[:-1], Flist[-1]
    prodB = float(np.prod(FB))
    eps = 1e-16
    lam = 1.0 - (1.0 - prodB)/(1.0 - prodB*FTR + eps)
    Fl  = lam*Fg + (1.0 - lam)*Far
    return Far, Fg, Fl

# =================== Exercise 2 tasks ===================
def bloch_coords(r):
    x = 2*np.real(r[:,0,1])
    y = -2*np.imag(r[:,0,1])
    z = np.real(r[:,0,0] - r[:,1,1])
    return x, y, z

def plot_bloch_trajectory(delta_MHz=1.0, T_us=20.0):
    """Start from |+>, show rotation around Z for t in [0, T]."""
    gamma_r = 1/540.0  # per µs
    Ls = lindblad_jumps(gamma_r)
    Ht = H_detuning_of_t(delta_MHz, T_us)

    # initial |+><+| embedded to 4x4
    rho_plus = np.array([[0.5,0.5],[0.5,0.5]], complex)
    rho0 = embed_2x2_to_4x4(rho_plus)

    ts, traj = evolve_rho(0.0, T_us, rho0, Ht, Ls, steps=max(1000, int(200*T_us)))
    r2 = np.array([extract_2x2_from_4x4(r) for r in traj])
    x,y,z = bloch_coords(r2)

    fig = plt.figure(figsize=(6,6))
    ax = fig.add_subplot(111, projection='3d')
    # wireframe sphere
    u = np.linspace(0, 2*np.pi, 60); v = np.linspace(0, np.pi, 30)
    xs = np.outer(np.cos(u), np.sin(v)); ys = np.outer(np.sin(u), np.sin(v)); zs = np.outer(np.ones_like(u), np.cos(v))
    ax.plot_wireframe(xs, ys, zs, linewidth=0.2, alpha=0.3)
    ax.plot(x, y, z, label=r"start $|+\rangle$, rotate about +Z")
    ax.set_xlabel("x"); ax.set_ylabel("y"); ax.set_zlabel("z")
    ax.set_title(f"Constant detuning: δ={delta_MHz} MHz, T={T_us} µs")
    ax.legend(); plt.tight_layout(); plt.show()

def optimize_T_for_Z(delta_MHz=1.0, T0_us=0.3):
    """Optimize the detuning duration T to realize Z (π phase)."""
    U_target = Z2
    gamma_r = 1/540.0
    Ls = lindblad_jumps(gamma_r)

    def make_evolver(T_us):
        Ht = H_detuning_of_t(delta_MHz, T_us)
        def evolve2x2(r2):
            r4 = embed_2x2_to_4x4(r2)
            _, tr = evolve_rho(0.0, T_us, r4, Ht, Ls, steps=max(1000, int(200*T_us))+1)
            return extract_2x2_from_4x4(tr[-1])
        return evolve2x2

    history = []

    def obj(Tarr):
        T = float(np.abs(Tarr[0]))
        Far, Fg, Fl = gate_fids_states_1q(U_target, make_evolver(T))
        history.append(Fl)
        return -Fl  # maximize Fl by minimizing negative

    # analytic expectation
    delta_rad = w(delta_MHz)
    T_pi_analytic = np.pi / delta_rad  # µs

    if SCIPY_OK:
        res = minimize(obj, x0=np.array([T0_us]), method="Nelder-Mead",
                       options={"maxiter": 200, "disp": False})
        T_best = float(np.abs(res.x[0]))
        Far, Fg, Fl = gate_fids_states_1q(U_target, make_evolver(T_best))
    else:
        # fallback coarse scan
        Ts = np.linspace(0.02, 3.0/max(1e-9, delta_MHz), 120)  # around expected scale
        best = (-1.0, Ts[0])
        for T in Ts:
            Far, Fg, Fl = gate_fids_states_1q(U_target, make_evolver(T))
            history.append(Fl)
            if Fl > best[0]: best = (Fl, T)
        Fl, T_best = best
        Far, Fg = None, None

    print(f"Optimized T*: {T_best:.9f} µs   |  analytic T_pi = {T_pi_analytic:.9f} µs")
    if Far is not None:
        print(f"Fidelities at T* — Farith={Far:.12f}, Fgeom={Fg:.12f}, Flambda={Fl:.12f}")
    else:
        print(f"Fidelity at T* — Flambda={Fl:.12f}")

    # plot convergence (by iteration index)
    plt.figure(figsize=(6,4))
    plt.plot(range(1, len(history)+1), history, marker="o")
    plt.xlabel("Iteration"); plt.ylabel("Fidelity (Flambda)")
    plt.title("Optimizing detuning duration T for a Z gate")
    plt.grid(True, alpha=0.3); plt.tight_layout(); plt.show()

    return T_best, T_pi_analytic, Fl

# =================== Run the exercise ===================
if __name__ == "__main__":
    # 1) Bloch evolution for constant detuning over 20 µs
    plot_bloch_trajectory(delta_MHz=1.0, T_us=20.0)

    # 2) Optimize T to realize a Z gate
    T_star, T_pi, Fl = optimize_T_for_Z(delta_MHz=1.0, T0_us=0.3)
    # Expect T* ~ T_pi = π/δ (e.g., δ=1 MHz -> T* ≈ 0.5 µs) and Fl ≈ 1.

# cz_arp_fast.py
# Neutral Atom Gates — Exercise 3: CZ via ARP (two atoms, Rydberg blockade)
# Optimized NumPy RK4 Lindblad with precomputed L†L, complex64, and fast defaults.

import numpy as np
import matplotlib.pyplot as plt

# ---- Optional SciPy (for nicer optimization); falls back to coarse scan if absent ----
try:
    from scipy.optimize import minimize
    SCIPY_OK = True
except Exception:
    SCIPY_OK = False

# =================== Global numerical knobs ===================
DT = np.complex64          # << speed: use complex64 (set to np.complex128 for max precision)
TWOPI = 2 * np.pi

FAST_STEPS_PER_US = 350    # << fast during dev
HEAVY_STEPS_PER_US = 1600  # << prettier plots
FAST_ITERS = 40            # << optimizer iterations (fast)
HEAVY_ITERS = 120          # << more thorough

def w(MHz):                # MHz -> rad / microsecond
    return (TWOPI * MHz).astype(np.float64) if isinstance(MHz, np.ndarray) else TWOPI * MHz

def dagger(A): return np.conjugate(A.T)

def op(i, j, d=4):
    M = np.zeros((d, d), dtype=DT); M[i, j] = 1.0
    return M

def eigh_sqrt_psd(A):
    A = (A + dagger(A)) * DT(0.5)
    ew, V = np.linalg.eigh(A.astype(np.complex128))  # eigens in float64 to keep stable
    ew = np.clip(ew, 0.0, None)
    out = (V * np.sqrt(ew)) @ dagger(V)
    return out.astype(DT)

def state_fidelity(rho, sigma):
    tr_r2 = np.real(np.trace(rho @ rho))
    tr_s2 = np.real(np.trace(sigma @ sigma))
    if abs(tr_r2 - 1.0) < 1e-10 and abs(tr_s2 - 1.0) < 1e-10:
        val = np.real(np.trace(rho @ sigma))
        return float(np.clip(val, 0.0, 1.0))
    A = eigh_sqrt_psd(rho) @ sigma @ eigh_sqrt_psd(rho)
    Froot = np.real(np.trace(eigh_sqrt_psd(A)))
    F = float(np.clip(Froot, 0.0, None))**2
    return float(np.clip(F, 0.0, 1.0))

# =================== Single-atom primitives ===================
I4 = np.eye(4, dtype=DT)
E00, E11, Err, Edd = op(0,0), op(1,1), op(2,2), op(3,3)
Er1, E1r = op(2,1), op(1,2)           # |r><1|, |1><r|
P_rr_single = Err

def A(X):  return np.kron(X, I4).astype(DT)
def B_(X): return np.kron(I4, X).astype(DT)

P_rr_rr = A(Err) @ B_(Err)

# =================== Lindblad RHS factory (precomputes L† and L†L) ===================
def make_rhs(H_of_t, Ls):
    Lds  = [dagger(L) for L in Ls]
    LdLs = [Lds[i] @ Ls[i] for i in range(len(Ls))]
    def rhs(rho, t_us):
        Ht = H_of_t(t_us)
        comm = -1j * (Ht @ rho - rho @ Ht)
        # use precomputed LdL
        acc = np.zeros_like(rho, dtype=DT)
        for i in range(len(Ls)):
            acc += Ls[i] @ rho @ Lds[i] - DT(0.5) * (LdLs[i] @ rho + rho @ LdLs[i])
        return comm + acc
    return rhs

def evolve_rho(t0, t1, rho0, rhs, steps):
    ts = np.linspace(t0, t1, steps + 1).astype(np.float64)
    dt = (t1 - t0) / steps
    rho = rho0.astype(DT, copy=True)
    out = [rho.copy()]
    for k in range(steps):
        t = ts[k]
        k1 = rhs(rho, t)
        k2 = rhs(rho + DT(0.5*dt) * k1, t + DT(0.5*dt))
        k3 = rhs(rho + DT(0.5*dt) * k2, t + DT(0.5*dt))
        k4 = rhs(rho + DT(dt)      * k3, t + DT(dt))
        rho = rho + DT(dt/6.0) * (k1 + 2*k2 + 2*k3 + k4)
        rho = (rho + dagger(rho)) * DT(0.5)        # clean hermiticity
        out.append(rho.copy())
    return ts, np.asarray(out, dtype=DT)

# =================== Decay channels (two atoms) ===================
def lindblad_jumps_twoatom(gamma_r_per_us, b0=1/16, b1=1/16, bd=7/8):
    L0A = np.sqrt(gamma_r_per_us*b0) * A(op(0,2))
    L1A = np.sqrt(gamma_r_per_us*b1) * A(op(1,2))
    LdA = np.sqrt(gamma_r_per_us*bd) * A(op(3,2))
    L0B = np.sqrt(gamma_r_per_us*b0) * B_(op(0,2))
    L1B = np.sqrt(gamma_r_per_us*b1) * B_(op(1,2))
    LdB = np.sqrt(gamma_r_per_us*bd) * B_(op(3,2))
    return [L0A.astype(DT), L1A.astype(DT), LdA.astype(DT),
            L0B.astype(DT), L1B.astype(DT), LdB.astype(DT)]

# =================== ARP pulses ===================
def arp_pulses(T_us, Omega_MHz, Delta_MHz, tau_frac):
    tau = tau_frac * T_us
    a = np.exp(-((T_us/4)/tau)**4)
    Omega0 = w(Omega_MHz)     # rad/us
    Delta0 = w(Delta_MHz)     # rad/us

    def Omega(t):
        if 0.0 <= t <= T_us:
            t0 = T_us/4 if t < T_us/2 else 3*T_us/4
            shape = (np.exp(-((t - t0)**4)/(tau**4)) - a) / (1.0 - a)
            return Omega0 * shape
        return 0.0

    def Delta(t):
        if 0.0 <= t <= T_us:
            return -Delta0 * np.cos(TWOPI * t / T_us)
        return 0.0

    return Omega, Delta

def make_H_twoatom(T_us, Omega_MHz, Delta_MHz, tau_frac, B_MHz):
    Ω, Δ = arp_pulses(T_us, Omega_MHz, Delta_MHz, tau_frac)
    Bshift = w(B_MHz)

    X01_A = A(Er1 + E1r)
    X01_B = B_(Er1 + E1r)
    PrA   = A(P_rr_single)
    PrB   = B_(P_rr_single)

    def H_of_t(t):
        return DT(0.5) * DT(Ω(t)) * (X01_A + X01_B) + DT(Δ(t)) * (PrA + PrB) + DT(Bshift) * P_rr_rr
    return H_of_t

# =================== Computational subspace & target ===================
def embed_4x4_to_16(r2q):
    rho = np.zeros((16,16), dtype=DT); rho[:4,:4] = r2q
    return rho
def extract_4x4_from_16(r):
    return r[:4,:4].astype(DT)

CZ = np.diag([1,1,1,-1]).astype(DT)

def test_set_2q():
    basis = [np.diag([1,0,0,0]).astype(DT),
             np.diag([0,1,0,0]).astype(DT),
             np.diag([0,0,1,0]).astype(DT),
             np.diag([0,0,0,1]).astype(DT)]
    plus = (DT(0.25) * np.ones((4,4), dtype=DT))  # |++><++|
    return basis, plus

def gate_fids_states_2q(U_target, evolve2q_fn):
    basis, TR = test_set_2q()
    F = []
    for rho_in in basis + [TR]:
        rho_t = U_target @ rho_in @ dagger(U_target)
        rho_i = evolve2q_fn(rho_in)
        F.append(state_fidelity(rho_t, rho_i))
    Far = float(np.mean(F))
    Fg  = float(np.prod(F)) ** (1/5)
    FB, FTR = F[:-1], F[-1]
    prodB = float(np.prod(FB))
    eps = 1e-16
    lam = 1.0 - (1.0 - prodB) / (1.0 - prodB * FTR + eps)
    Fl  = lam * Fg + (1.0 - lam) * Far
    return Far, Fg, Fl

# =================== Diagnostics ===================
def idx(iA,iB): return iA*4 + iB

def populations_from_traj(traj):
    diag = np.real(traj[:, np.arange(16), np.arange(16)])
    return {
        "P_10":    diag[:, idx(1,0)],
        "P_r0":    diag[:, idx(2,0)],
        "P_1r":    diag[:, idx(1,2)],
        "P_rr":    diag[:, idx(2,2)],
        "P_11":    diag[:, idx(1,1)],
        "P_any_r": diag[:, idx(2,0)] + diag[:, idx(0,2)] + diag[:, idx(2,1)] + diag[:, idx(1,2)] +
                   diag[:, idx(2,3)] + diag[:, idx(3,2)] + diag[:, idx(2,2)]
    }

# =================== High-level routines (using shared RHS) ===================
def simulate_and_plot_pulses_and_pop(T_us=0.54, Omega_MHz=17.0, Delta_MHz=23.0, B_MHz=200.0,
                                     tau_frac=0.175, gamma_r_inv_us=540.0,
                                     steps_per_us=FAST_STEPS_PER_US):
    Ht = make_H_twoatom(T_us, Omega_MHz, Delta_MHz, tau_frac, B_MHz)
    gamma = 1.0 / gamma_r_inv_us
    Ls = lindblad_jumps_twoatom(gamma)
    rhs = make_rhs(Ht, Ls)

    # pulses
    Ω, Δ = arp_pulses(T_us, Omega_MHz, Delta_MHz, tau_frac)
    ts = np.linspace(0, T_us, 1201)
    plt.figure(figsize=(7,5))
    plt.subplot(2,1,1); plt.plot(ts, np.array([Ω(t) for t in ts])/TWOPI); plt.ylabel(r"$\Omega_{1r}$ (MHz)")
    plt.subplot(2,1,2); plt.plot(ts, np.array([Δ(t) for t in ts])/TWOPI); plt.ylabel(r"$\Delta_r$ (MHz)"); plt.xlabel("time (µs)")
    plt.suptitle("ARP pulses"); plt.tight_layout(); plt.show()

    # start |10>
    psi10 = np.zeros((16,1), dtype=DT); psi10[idx(1,0),0] = 1.0
    rho0 = psi10 @ dagger(psi10)
    steps = max(1000, int(steps_per_us * T_us))
    ts, traj = evolve_rho(0.0, T_us, rho0, rhs, steps=steps)

    pops = populations_from_traj(traj)
    plt.figure(figsize=(7,4.5))
    for k, lbl in [("P_10","|10⟩"),("P_r0","|r0⟩"),("P_1r","|1r⟩"),("P_rr","|rr⟩"),("P_11","|11⟩"),("P_any_r","any Rydberg")]:
        plt.plot(ts, pops[k], label=lbl)
    plt.xlabel("time (µs)"); plt.ylabel("population"); plt.title("|10⟩ dynamics")
    plt.legend(); plt.grid(True, alpha=0.3); plt.tight_layout(); plt.show()

def cz_fidelity_for_params(T_us=0.54, Omega_MHz=17.0, Delta_MHz=23.0, B_MHz=200.0,
                           tau_frac=0.175, gamma_r_inv_us=540.0,
                           steps_per_us=FAST_STEPS_PER_US, return_leak=False):
    Ht  = make_H_twoatom(T_us, Omega_MHz, Delta_MHz, tau_frac, B_MHz)
    gam = 1.0 / gamma_r_inv_us
    Ls  = lindblad_jumps_twoatom(gam)
    rhs = make_rhs(Ht, Ls)

    steps = max(1000, int(steps_per_us * T_us))

    def evolve2q(rho2):
        r16 = embed_4x4_to_16(rho2)
        _, traj = evolve_rho(0.0, T_us, r16, rhs, steps=steps)
        r2 = extract_4x4_from_16(traj[-1])
        if return_leak:
            diag = np.real(traj[-1, np.arange(16), np.arange(16)])
            any_r = 0.0
            for iA in range(4):
                for iB in range(4):
                    if iA == 2 or iB == 2:
                        any_r += diag[idx(iA,iB)]
            return r2, any_r
        return r2

    if return_leak:
        def eplain(r2): return evolve2q(r2)[0]
        Far, Fg, Fl = gate_fids_states_2q(CZ, eplain)
        leak = evolve2q(np.diag([0,0,0,1]).astype(DT))[1]
        return Far, Fg, Fl, leak
    else:
        return gate_fids_states_2q(CZ, evolve2q)

# =================== Optimization wrappers ===================
def optimize_params_for_B(B_MHz, x0=(0.54, 17.0, 23.0, 0.175),
                          gamma_r_inv_us=540.0, steps_per_us=FAST_STEPS_PER_US,
                          iters_cap=FAST_ITERS):
    hist = []
    def pack(x):
        T  = max(0.05, float(abs(x[0])))
        Om = max(1.0, float(abs(x[1])))
        De = max(1.0, float(abs(x[2])))
        tf = min(0.49, max(0.05, float(abs(x[3]))))
        return T, Om, De, tf

    def obj(x):
        T, Om, De, tf = pack(x)
        Far, Fg, Fl = cz_fidelity_for_params(T, Om, De, B_MHz, tf,
                                             gamma_r_inv_us=gamma_r_inv_us,
                                             steps_per_us=steps_per_us)
        hist.append(Fl)
        return -Fl

    if SCIPY_OK:
        res = minimize(obj, x0=np.array(x0), method="Nelder-Mead",
                       options={"maxiter": iters_cap, "disp": False})
        Tb, Omb, Deb, tfb = pack(res.x)
        Far, Fg, Fl = cz_fidelity_for_params(Tb, Omb, Deb, B_MHz, tfb,
                                             gamma_r_inv_us=gamma_r_inv_us,
                                             steps_per_us=steps_per_us)
    else:
        grid_T  = np.linspace(0.25, 0.8, 6)
        grid_Om = np.linspace(10,  26, 5)
        grid_De = np.linspace(14,  34, 5)
        grid_tf = np.linspace(0.12,0.28,5)
        best = (-1.0, None)
        for T in grid_T:
            for Om in grid_Om:
                for De in grid_De:
                    for tf in grid_tf:
                        Far, Fg, Fl = cz_fidelity_for_params(T, Om, De, B_MHz, tf,
                                                             gamma_r_inv_us=gamma_r_inv_us,
                                                             steps_per_us=steps_per_us)
                        hist.append(Fl)
                        if Fl > best[0]: best = (Fl, (T, Om, De, tf))
        Fl, (Tb, Omb, Deb, tfb) = best
        Far, Fg = None, None

    print(f"[B={B_MHz:>4.0f} MHz] best -> T={Tb:.4f} µs, Ω/2π={Omb:.2f} MHz, Δ/2π={Deb:.2f} MHz, τ/T={tfb:.3f}")
    print("  Flambda={:.6f}{}".format(
        Fl, "" if Far is None else f", Farith={Far:.6f}, Fgeom={Fg:.6f}"))

    plt.figure(figsize=(6,4))
    plt.plot(range(1, len(hist)+1), hist, marker="o")
    plt.xlabel("Iteration"); plt.ylabel("Fidelity (Flambda)")
    plt.title(f"Optimize (T,Ω,Δ,τ/T) at B={B_MHz} MHz")
    plt.grid(True, alpha=0.3); plt.tight_layout(); plt.show()

    return {"B":B_MHz, "T":Tb, "Omega":Omb, "Delta":Deb, "tau_frac":tfb, "Flambda":Fl}

def sweep_blockade_and_optimize(B_list=(200, 400, 800),   # << keep small in FAST mode
                                x0=(0.54, 17.0, 23.0, 0.175),
                                gamma_r_inv_us=540.0,
                                steps_per_us=FAST_STEPS_PER_US,
                                iters_cap=FAST_ITERS):
    rows = []
    seed = list(x0)
    for B in B_list:
        res = optimize_params_for_B(B, x0=tuple(seed),
                                    gamma_r_inv_us=gamma_r_inv_us,
                                    steps_per_us=steps_per_us,
                                    iters_cap=iters_cap)
        rows.append(res)
        seed = (res["T"], res["Omega"], res["Delta"], res["tau_frac"])
    # plot fidelity vs B
    plt.figure(figsize=(6,4))
    plt.plot([r["B"] for r in rows], [r["Flambda"] for r in rows], marker="o")
    plt.xlabel("Blockade B / 2π (MHz)"); plt.ylabel("Best Flambda")
    plt.title("Optimized CZ fidelity vs blockade (FAST sweep)")
    plt.grid(True, alpha=0.3); plt.tight_layout(); plt.show()
    return rows

# =================== Main: FAST by default ===================
if __name__ == "__main__":
    # Initial params from the handout
    T0, Om0, De0, B0, tau0 = 0.54, 17.0, 23.0, 200.0, 0.175

    # --- FAST preview (seconds) ---
    simulate_and_plot_pulses_and_pop(T0, Om0, De0, B0, tau0,
                                     steps_per_us=FAST_STEPS_PER_US)

    Far, Fg, Fl, leak = cz_fidelity_for_params(T0, Om0, De0, B0, tau0,
                                               steps_per_us=FAST_STEPS_PER_US,
                                               return_leak=True)
    print(f"Initial params -> Far={Far:.6f}, Fg={Fg:.6f}, Fl={Fl:.6f}, leak≈{leak:.3e}")

    # One quick optimization at B=200 MHz
    optimize_params_for_B(200, iters_cap=FAST_ITERS, steps_per_us=FAST_STEPS_PER_US)

    # Small blockade sweep (FAST). For the full study, use the HEAVY block below.
    sweep_blockade_and_optimize(B_list=(200, 400, 800),
                                steps_per_us=FAST_STEPS_PER_US,
                                iters_cap=FAST_ITERS)

# cz_timeopt_batched_fast.py
# Bonus Exercise: Time-Optimal CZ via logistic-on/off amplitude + chirped, modulated detuning
# Heavy parts optimized: pre-sampled waveforms + batched RK4 for 5 density matrices.

import numpy as np
import matplotlib.pyplot as plt

try:
    from scipy.optimize import minimize
    SCIPY_OK = True
except Exception:
    SCIPY_OK = False

# ==================== Global numeric knobs ====================
DT = np.complex64           # use np.complex128 for final numbers
TWOPI = 2*np.pi

FAST_STEPS_PER_US  = 350    # dev/tuning
HEAVY_STEPS_PER_US = 1600   # final plots / numbers
FAST_ITERS  = 45
HEAVY_ITERS = 120

def w(MHz): return TWOPI * MHz          # MHz -> rad/us
def dagger(A): return np.conjugate(A.T)

# -------------------- density-matrix fidelities --------------------
def eigh_sqrt_psd(A):
    A = (A + dagger(A)) * DT(0.5)
    ew, V = np.linalg.eigh(A.astype(np.complex128))
    ew = np.clip(ew, 0.0, None)
    return (V*np.sqrt(ew)) @ dagger(V)

def state_fidelity(rho, sigma):
    tr_r2 = np.real(np.trace(rho @ rho))
    tr_s2 = np.real(np.trace(sigma @ sigma))
    if abs(tr_r2-1.0) < 1e-10 and abs(tr_s2-1.0) < 1e-10:
        return float(np.clip(np.real(np.trace(rho @ sigma)), 0.0, 1.0))
    A = eigh_sqrt_psd(rho) @ sigma @ eigh_sqrt_psd(rho)
    Froot = np.real(np.trace(eigh_sqrt_psd(A)))
    F = float(np.clip(Froot, 0.0, None))**2
    return float(np.clip(F, 0.0, 1.0))

# ==================== single-atom primitives ====================
I4 = np.eye(4, dtype=DT)

def op(i,j,d=4):
    M = np.zeros((d,d), dtype=DT); M[i,j] = 1.0; return M

E00, E11, Err, Edd = op(0,0), op(1,1), op(2,2), op(3,3)
Er1, E1r = op(2,1), op(1,2)                         # |r><1|, |1><r|
P_rr_single = Err

def A(X):  return np.kron(X, I4).astype(DT)
def B_(X): return np.kron(I4, X).astype(DT)

P_rr_rr = A(Err) @ B_(Err)

# Fixed Hamiltonian pieces (time dependence enters via scalars Ω(t), Δ(t))
H_OMEGA = 0.5 * (A(Er1 + E1r) + B_(Er1 + E1r))      # couples |1> <-> |r|
H_DELTA = (A(P_rr_single) + B_(P_rr_single))        # Rydberg detuning
def H_CONST_B(B_MHz): return w(B_MHz) * P_rr_rr     # blockade shift on |rr>

# ==================== Lindblad channels (2 atoms) ====================
def lindblad_jumps_twoatom(gamma_r_per_us, b0=1/16, b1=1/16, bd=7/8):
    L0A = np.sqrt(gamma_r_per_us*b0) * A(op(0,2))
    L1A = np.sqrt(gamma_r_per_us*b1) * A(op(1,2))
    LdA = np.sqrt(gamma_r_per_us*bd) * A(op(3,2))
    L0B = np.sqrt(gamma_r_per_us*b0) * B_(op(0,2))
    L1B = np.sqrt(gamma_r_per_us*b1) * B_(op(1,2))
    LdB = np.sqrt(gamma_r_per_us*bd) * B_(op(3,2))
    Ls  = [L0A, L1A, LdA, L0B, L1B, LdB]
    Lds = [dagger(L) for L in Ls]
    LdLs= [Lds[i] @ Ls[i] for i in range(len(Ls))]
    return [L.astype(DT) for L in Ls], [Ld.astype(DT) for Ld in Lds], [LdL.astype(DT) for LdL in LdLs]

# ==================== time-optimal pulses (vectorized) ====================
def timeopt_waves_preset(tg_us, Omega0_MHz, Ddot_MHz_per_us, a_MHz, f_MHz, tau_env_frac, steps):
    """
    Pre-samples Ω(t) and Δ(t) on the grid t_k = k*dt, k=0..steps.
    Returns arrays Om[steps+1], De[steps+1] in rad/us, and mid-point arrays length steps.
    """
    tau_e_us = 0.001825  # 1.825 ns
    t0 = tg_us / 2.0
    dt = tg_us / steps
    ts = np.linspace(0.0, tg_us, steps+1)

    # clip to avoid overflow in exp
    def logistic(x): return 1.0 / (1.0 + np.exp(-np.clip(x, -60.0, 60.0)))

    s_on  = logistic((ts - 20*tau_e_us)/tau_e_us)
    s_off = logistic((tg_us - 20*tau_e_us - ts)/tau_e_us)
    Om = w(Omega0_MHz) * (s_on + s_off - 1.0)              # rad/us

    tau_env = np.clip(tau_env_frac, 0.05, 0.49) * tg_us
    env  = np.exp(-((ts - t0)/tau_env)**4)
    De   = w(Ddot_MHz_per_us) * ts + w(a_MHz) * np.sin(w(f_MHz)*(ts - t0)) * env  # rad/us

    # midpoints for RK4 k2/k3 (linear interpolation)
    Om_mid = 0.5*(Om[:-1] + Om[1:])
    De_mid = 0.5*(De[:-1] + De[1:])

    return dt, Om.astype(np.float64), De.astype(np.float64), Om_mid.astype(np.float64), De_mid.astype(np.float64)

# ==================== batched RK4 (5 states at once) ====================
def rk4_batched(Om, De, Om_mid, De_mid, dt, H_const, Ls, Lds, LdLs, rho_batch):
    """
    Om, De: arrays len N+1; Om_mid, De_mid: len N; dt: scalar; N = number of steps.
    rho_batch: shape (B, 16, 16) complex (B=5 here).
    """
    N = len(Om) - 1
    HΩ = H_OMEGA
    HΔ = H_DELTA

    rho = rho_batch.copy()

    # local helpers using einsum for batched matmuls
    def comm(H, X):  # -i(HX - XH)
        HX = np.einsum('ab,kbc->kac', H, X, optimize=True)
        XH = np.einsum('kab,bc->kac', X, H, optimize=True)
        return -1j*(HX - XH)

    def dissipate(X):
        acc = np.zeros_like(X)
        for L, Ld, LdL in zip(Ls, Lds, LdLs):
            t1 = np.einsum('ab,kbc->kac', L, X,   optimize=True)
            t1 = np.einsum('kab,bc->kac', t1, Ld, optimize=True)
            t2 = np.einsum('ab,kbc->kac', LdL, X, optimize=True)
            t3 = np.einsum('kab,bc->kac', X, LdL, optimize=True)
            acc += t1 - 0.5*(t2 + t3)
        return acc

    for i in range(N):
        # assemble H at t_i, t_{i+1/2}, t_{i+1}
        H1 = (Om[i]    * HΩ + De[i]    * HΔ + H_const).astype(DT, copy=False)
        Hm = (Om_mid[i]* HΩ + De_mid[i]* HΔ + H_const).astype(DT, copy=False)
        H4 = (Om[i+1]  * HΩ + De[i+1]  * HΔ + H_const).astype(DT, copy=False)

        k1 = comm(H1, rho)                  + dissipate(rho)
        k2 = comm(Hm, rho + DT(0.5*dt)*k1) + dissipate(rho + DT(0.5*dt)*k1)
        k3 = comm(Hm, rho + DT(0.5*dt)*k2) + dissipate(rho + DT(0.5*dt)*k2)
        k4 = comm(H4, rho + DT(dt)*k3)     + dissipate(rho + DT(dt)*k3)

        rho = rho + DT(dt/6.0) * (k1 + 2*k2 + 2*k3 + k4)
        rho = (rho + np.conjugate(np.swapaxes(rho, -1, -2))) * DT(0.5)  # enforce hermiticity

    return rho

# ==================== computational subspace plumbing ====================
def embed_4x4_to_16_batch(rhos_4):
    B = rhos_4.shape[0]
    r = np.zeros((B, 16, 16), dtype=DT)
    r[:, :4, :4] = rhos_4
    return r

def extract_4x4_from_16_batch(rhos_16):
    return rhos_16[:, :4, :4].astype(DT)

CZ = np.diag([1,1,1,-1]).astype(DT)

def make_test_set_2q():
    basis = [np.diag([1,0,0,0]).astype(DT),
             np.diag([0,1,0,0]).astype(DT),
             np.diag([0,0,1,0]).astype(DT),
             np.diag([0,0,0,1]).astype(DT)]
    plus = DT(0.25)*np.ones((4,4), dtype=DT)  # |++><++|
    return np.stack(basis + [plus], axis=0)   # shape (5,4,4)

def gate_fids_states_batched(Ut, rho_in_4, rho_out_4):
    # Compute target images
    Ut_d = dagger(Ut)
    target_4 = np.einsum('ab,kbc,cd->kad', Ut, rho_in_4, Ut_d, optimize=True)
    Fs = [state_fidelity(target_4[k], rho_out_4[k]) for k in range(rho_in_4.shape[0])]
    Far = float(np.mean(Fs))
    Fg  = float(np.prod(Fs))**(1/len(Fs))
    prodB = float(np.prod(Fs[:-1])); FTR = Fs[-1]
    lam = 1.0 - (1.0 - prodB)/(1.0 - prodB*FTR + 1e-16)
    Fl  = lam*Fg + (1.0 - lam)*Far
    return Far, Fg, Fl, Fs

# ==================== top-level fidelity (time-opt, batched) ====================
def cz_fidelity_timeopt_batched(tg_us, Om0_MHz, Ddot_MHz_per_us, a_MHz, f_MHz, tau_frac,
                                B_MHz, gamma_r_inv_us=540.0, steps_per_us=FAST_STEPS_PER_US,
                                want_leak=False):
    # precompute waveforms
    steps = max(1000, int(steps_per_us * tg_us))
    dt, Om, De, Om_mid, De_mid = timeopt_waves_preset(
        tg_us, Om0_MHz, Ddot_MHz_per_us, a_MHz, f_MHz, tau_frac, steps
    )
    # jumps
    gamma = 1.0 / gamma_r_inv_us
    Ls, Lds, LdLs = lindblad_jumps_twoatom(gamma)

    # Hamiltonian constant part
    Hc = H_CONST_B(B_MHz)

    # initial 5 states in computational subspace (4x4) -> embed to 16x16 batch
    rho_in_4 = make_test_set_2q()
    rho0 = embed_4x4_to_16_batch(rho_in_4)      # (5,16,16)

    # run batched RK4
    rhoT = rk4_batched(Om, De, Om_mid, De_mid, dt, Hc, Ls, Lds, LdLs, rho0)

    # project back to 4x4 and compute gate fidelities
    rho_out_4 = extract_4x4_from_16_batch(rhoT)
    Far, Fg, Fl, Fs = gate_fids_states_batched(CZ, rho_in_4, rho_out_4)

    leak = None
    if want_leak:
        # leakage = population in any state with at least one |r> (sum of diag outside 4x4 block)
        diag = np.real(rhoT[-2].diagonal())  # (choose |11> index k=3 -> position -2 in our list? we used order [00,01,10,11,++]
        # safer: compute from last batch element corresponding to |11> which is index 3
        diag11 = np.real(rhoT[3].diagonal())
        any_r = 0.0
        for iA in range(4):
            for iB in range(4):
                if iA == 2 or iB == 2:
                    any_r += diag11[iA*4 + iB]
        leak = float(any_r)

    return Far, Fg, Fl, leak

# ==================== plotting helpers ====================
def plot_timeopt_pulses(tg_us, Om0_MHz, Ddot_MHz_per_us, a_MHz, f_MHz, tau_frac):
    steps = 1200
    dt, Om, De, _, _ = timeopt_waves_preset(tg_us, Om0_MHz, Ddot_MHz_per_us, a_MHz, f_MHz, tau_frac, steps)
    ts = np.linspace(0.0, tg_us, steps+1)
    plt.figure(figsize=(7,5))
    plt.subplot(2,1,1); plt.plot(ts, Om/TWOPI); plt.ylabel(r"$\Omega_{1r}$ (MHz)")
    plt.subplot(2,1,2); plt.plot(ts, De/TWOPI); plt.ylabel(r"$\Delta_r$ (MHz)"); plt.xlabel("time (µs)")
    plt.suptitle("Time-optimal pulse (pre-sampled)"); plt.tight_layout(); plt.show()

# ==================== optimization wrappers ====================
def optimize_timeopt_for_B(B_MHz,
                           x0=(0.40, 18.0, 30.0, 12.0, 4.0, 0.18),  # (tg, Om0, Ddot, a, f, tau_frac)
                           gamma_r_inv_us=540.0, steps_per_us=FAST_STEPS_PER_US, iters=FAST_ITERS):
    hist=[]
    def pack(x):
        tg  = max(0.08, float(abs(x[0])))
        Om0 = max(4.0,  float(abs(x[1])))
        Dd  = float(x[2])                  # signed slope allowed
        a   = max(0.0,  float(abs(x[3])))
        f   = max(0.5,  float(abs(x[4])))
        tf  = min(0.49, max(0.05, float(abs(x[5]))))
        return tg, Om0, Dd, a, f, tf

    def obj(x):
        tg, Om0, Dd, a, f, tf = pack(x)
        Far, Fg, Fl, _ = cz_fidelity_timeopt_batched(tg, Om0, Dd, a, f, tf, B_MHz,
                                                     gamma_r_inv_us=gamma_r_inv_us,
                                                     steps_per_us=steps_per_us)
        hist.append(Fl)
        return -Fl

    if SCIPY_OK:
        res = minimize(obj, x0=np.array(x0), method="Nelder-Mead",
                       options={"maxiter": iters, "disp": False})
        tg, Om0, Dd, a, f, tf = pack(res.x)
        Far, Fg, Fl, leak = cz_fidelity_timeopt_batched(tg, Om0, Dd, a, f, tf, B_MHz,
                                                        gamma_r_inv_us=gamma_r_inv_us,
                                                        steps_per_us=steps_per_us, want_leak=True)
    else:
        # coarse grid fallback
        grid_tg = np.linspace(0.2, 0.7, 6)
        grid_Om = np.linspace(8,  28, 6)
        grid_Dd = np.linspace(10, 60, 6)
        grid_a  = np.linspace(4,  20, 5)
        grid_f  = np.linspace(2,  8,  4)
        grid_tf = np.linspace(0.10, 0.28, 5)
        best = (-1.0, None)
        for tg in grid_tg:
            for Om0 in grid_Om:
                for Dd in grid_Dd:
                    for a in grid_a:
                        for f in grid_f:
                            for tf in grid_tf:
                                Far, Fg, Fl, _ = cz_fidelity_timeopt_batched(tg, Om0, Dd, a, f, tf, B_MHz,
                                                                             gamma_r_inv_us=gamma_r_inv_us,
                                                                             steps_per_us=steps_per_us)
                                hist.append(Fl)
                                if Fl > best[0]: best = (Fl, (tg, Om0, Dd, a, f, tf))
        Fl, (tg, Om0, Dd, a, f, tf) = best
        Far, Fg, leak = None, None, None

    print(f"[B={B_MHz:>4.0f} MHz] time-opt best:")
    print(f"  t_g={tg:.4f} µs, Ω0/2π={Om0:.2f} MHz, ẊΔ={Dd:.2f} MHz/µs, a/2π={a:.2f} MHz, f={f:.2f} MHz, τ/t_g={tf:.3f}")
    print("  Flambda={:.6f}{}".format(Fl, "" if Far is None else f", Farith={Far:.6f}, Fgeom={Fg:.6f}"))
    if leak is not None:
        print(f"  est. leakage (|11⟩) ≈ {leak:.3e}")

    plt.figure(figsize=(6,4))
    plt.plot(range(1,len(hist)+1), hist, marker='o')
    plt.xlabel("Iteration"); plt.ylabel("Fidelity (Flambda)")
    plt.title(f"Time-opt param search at B={B_MHz} MHz"); plt.grid(True, alpha=0.3); plt.tight_layout(); plt.show()

    return {"B":B_MHz,"tg":tg,"Omega0":Om0,"Ddot":Dd,"a":a,"f":f,"tau_frac":tf,"Flambda":Fl}

def sweep_B_timeopt(B_list=(50,100,200,300),
                    x0=(0.40,18.0,30.0,12.0,4.0,0.18),
                    gamma_r_inv_us=540.0, steps_per_us=FAST_STEPS_PER_US, iters=FAST_ITERS):
    rows=[]; seed=list(x0)
    for B in B_list:
        res = optimize_timeopt_for_B(B, x0=tuple(seed),
                                     gamma_r_inv_us=gamma_r_inv_us,
                                     steps_per_us=steps_per_us, iters=iters)
        rows.append(res)
        seed = (res["tg"],res["Omega0"],res["Ddot"],res["a"],res["f"],res["tau_frac"])
    plt.figure(figsize=(6,4))
    plt.plot([r["B"] for r in rows], [r["Flambda"] for r in rows], marker='o')
    plt.xlabel("Blockade B / 2π (MHz)"); plt.ylabel("Best Flambda")
    plt.title("Time-optimal CZ: best fidelity vs blockade (FAST)"); plt.grid(True, alpha=0.3); plt.tight_layout(); plt.show()
    return rows

# ==================== quick demo / FAST default ====================
if __name__ == "__main__":
    # seed parameters (tune freely)
    tg0, Om0, Dd0, a0, f0, tf0 = 0.40, 18.0, 30.0, 12.0, 4.0, 0.18
    B0 = 200.0

    # Preview pulses
    plot_timeopt_pulses(tg0, Om0, Dd0, a0, f0, tf0)

    # Single-point fidelity (FAST)
    Far, Fg, Fl, leak = cz_fidelity_timeopt_batched(tg0, Om0, Dd0, a0, f0, tf0, B0,
                                                    steps_per_us=FAST_STEPS_PER_US, want_leak=True)
    print(f"Time-opt seed @ B={B0:.0f} MHz -> Far={Far:.6f}, Fg={Fg:.6f}, Fl={Fl:.6f}, leak≈{leak:.3e}")

    # One quick optimization
    optimize_timeopt_for_B(B0, x0=(tg0,Om0,Dd0,a0,f0,tf0),
                           steps_per_us=FAST_STEPS_PER_US, iters=FAST_ITERS)

    # FAST multi-B sweep (extend B_list for a fuller table)
    sweep_B_timeopt(B_list=(50,100,200,300),
                    x0=(tg0,Om0,Dd0,a0,f0,tf0),
                    steps_per_us=FAST_STEPS_PER_US, iters=FAST_ITERS)

    # HEAVY / final-quality run (uncomment when ready):
    # DT = np.complex128
    # optimize_timeopt_for_B(200, x0=(tg0,Om0,Dd0,a0,f0,tf0),
    #                        steps_per_us=HEAVY_STEPS_PER_US, iters=HEAVY_ITERS)
    # sweep_B_timeopt(B_list=(50,100,200,300),
    #                 x0=(tg0,Om0,Dd0,a0,f0,tf0),
    #                 steps_per_us=HEAVY_STEPS_PER_US, iters=HEAVY_ITERS)