# -*- coding: utf-8 -*-
"""SoftwareLab_Module5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dstgzYF7eOlPHnt4G6bEk6yBEAm8IJQp
"""

!pip -q install qiskit qiskit-experiments qutip qiskit-aer

import numpy as np

# =================== Units & basic helpers ===================

DT = np.complex128
TWOPI = 2.0 * np.pi

def w(MHz):
    """Frequency in MHz -> angular frequency in rad / microsecond."""
    return TWOPI * MHz

def dagger(A):
    """Conjugate transpose."""
    return np.conjugate(A.T)

def op(i, j, d=4):
    """|i><j| in dimension d."""
    M = np.zeros((d, d), dtype=DT)
    M[i, j] = 1.0
    return M


# =================== Single-atom (4-level) primitives ===================

# Basis: |0>, |1>, |r>, |d>
I4 = np.eye(4, dtype=DT)
E00, E11, Err, Edd = op(0, 0), op(1, 1), op(2, 2), op(3, 3)
Er1, E1r = op(2, 1), op(1, 2)          # |r><1|, |1><r|
P_rr_single = Err                      # projector onto |r>

# Pauli-like operators on the { |0>, |1> } subspace, embedded in 4D
X01   = op(0, 1) + op(1, 0)
Z01_4 = op(0, 0) - op(1, 1)


# =================== 1Q Hamiltonians ===================

def H_of_t_Omega01(Omega0_MHz, t0_us, sigma_us):
    """
    Gaussian Rabi drive on the |1> <-> |r> transition,
    implemented as (Ω01(t)/2) * X01 (embedded in 4-level space).
    """
    Omega0 = w(Omega0_MHz)  # rad/us

    def H(t_us):
        Omega_t = Omega0 * np.exp(-((t_us - t0_us) ** 2) / (2.0 * sigma_us ** 2))
        return 0.5 * Omega_t * X01
    return H


def H_detuning_of_t(delta_MHz, T_det_us):
    """
    H(t) = (δ/2) * Z01_4 for 0 <= t < T_det, else 0.
    Used for Z(π) gates via detuning.
    """
    delta = w(delta_MHz)  # rad/us

    def H(t_us):
        if 0.0 <= t_us < T_det_us:
            return 0.5 * delta * Z01_4
        else:
            return np.zeros((4, 4), dtype=DT)
    return H


# =================== 1Q Lindblad jumps (4-level atom) ===================

def lindblad_jumps(gamma_r_per_us, b0=1/16, b1=1/16, bd=7/8):
    """
    Decay r -> {0,1,d} with branching ratios b0,b1,bd.
    gamma_r_per_us is the total decay rate out of |r>.
    """
    L0 = np.sqrt(gamma_r_per_us * b0) * op(0, 2)  # |0><r|
    L1 = np.sqrt(gamma_r_per_us * b1) * op(1, 2)  # |1><r|
    Ld = np.sqrt(gamma_r_per_us * bd) * op(3, 2)  # |d><r|
    return [L0, L1, Ld]


# =================== Generic Lindblad RK4 integrator ===================

def lindblad_rhs(rho, t_us, H_of_t, Ls):
    """
    dρ/dt = -i [H(t), ρ] + Σ_L (LρL† - 1/2 {L†L, ρ})
    rho: (N,N) array, H_of_t(t) -> (N,N), Ls: list of (N,N).
    """
    Ht = H_of_t(t_us)
    comm = -1j * (Ht @ rho - rho @ Ht)

    diss = np.zeros_like(rho, dtype=DT)
    for L in Ls:
        Ld = dagger(L)
        diss += L @ rho @ Ld - 0.5 * (Ld @ L @ rho + rho @ Ld @ L)

    return comm + diss


def evolve_rho(tspan_us, rho0, H_of_t, Ls, steps=4000):
    """
    RK4 integrator for Lindblad dynamics over [t0, t1] in microseconds.
    Returns (ts, trajectory) where trajectory[k] is ρ(t_k).
    """
    t0, t1 = float(tspan_us[0]), float(tspan_us[1])
    ts = np.linspace(t0, t1, steps + 1)
    dt = (t1 - t0) / steps

    rho = rho0.astype(DT)
    traj = [rho.copy()]

    for k in range(steps):
        t = ts[k]
        k1 = lindblad_rhs(rho, t, H_of_t, Ls)
        k2 = lindblad_rhs(rho + 0.5 * dt * k1, t + 0.5 * dt, H_of_t, Ls)
        k3 = lindblad_rhs(rho + 0.5 * dt * k2, t + 0.5 * dt, H_of_t, Ls)
        k4 = lindblad_rhs(rho + dt * k3,       t + dt,       H_of_t, Ls)
        rho = rho + (dt / 6.0) * (k1 + 2*k2 + 2*k3 + k4)

        # enforce Hermiticity (and keep trace ≈ 1)
        rho = 0.5 * (rho + dagger(rho))
        traj.append(rho.copy())

    return ts, np.array(traj, dtype=DT)


# =================== 1Q embed / extract + pulse wrapper ===================

def embed_2x2_to_4x4(rho2):
    """Embed 2x2 computational density matrix into 4x4 (|0>,|1>,|r>,|d>) space."""
    rho4 = np.zeros((4, 4), dtype=DT)
    rho4[:2, :2] = rho2
    return rho4


def extract_2x2_from_4x4(rho4):
    """Project 4x4 single-atom density matrix back onto {|0>,|1>}."""
    return rho4[:2, :2].astype(DT)


def simulate_pulse_return_2x2(Omega0_MHz, sigma_us,
                              t0_us=0.0, gamma_r_inv_us=540.0,
                              steps=4000):
    """
    Module-2 helper:
    Simulates a Gaussian Ω01 pulse starting from |0> and |1>.

    Returns:
        ts, traj0, traj1, pulse_evolve_fn, H_of_t, Ls
      - traj0, traj1 are 4x4 trajectories for initial |0>, |1>
      - pulse_evolve_fn(rho2x2) evolves arbitrary 2x2 state under this pulse
    """
    gamma_r = 1.0 / gamma_r_inv_us  # per microsecond
    Ht = H_of_t_Omega01(Omega0_MHz, t0_us, sigma_us)
    Ls = lindblad_jumps(gamma_r, b0=1/16, b1=1/16, bd=7/8)
    tspan = (t0_us - 6.0 * sigma_us, t0_us + 6.0 * sigma_us)

    rho0 = embed_2x2_to_4x4(np.array([[1, 0],
                                      [0, 0]], dtype=DT))
    rho1 = embed_2x2_to_4x4(np.array([[0, 0],
                                      [0, 1]], dtype=DT))

    ts, traj0 = evolve_rho(tspan, rho0, Ht, Ls, steps=steps)
    _,  traj1 = evolve_rho(tspan, rho1, Ht, Ls, steps=steps)

    def pulse_evolve_fn(rho2x2):
        rho4 = embed_2x2_to_4x4(rho2x2.astype(DT))
        _, tr = evolve_rho(tspan, rho4, Ht, Ls, steps=steps)
        return extract_2x2_from_4x4(tr[-1])

    return ts, traj0, traj1, pulse_evolve_fn, Ht, Ls


# =================== Two-atom helpers (for CZ) ===================

def A(X):
    """Act X on atom A and identity on B."""
    return np.kron(X.astype(DT), I4).astype(DT)

def B_(X):
    """Act X on atom B and identity on A."""
    return np.kron(I4, X.astype(DT)).astype(DT)

P_rr_rr = A(Err) @ B_(Err)   # projector onto |rr>


def lindblad_jumps_twoatom(gamma_r_per_us, b0=1/16, b1=1/16, bd=7/8):
    """
    Two-atom decay channels, each atom decays r -> {0,1,d}.
    """
    L0A = np.sqrt(gamma_r_per_us * b0) * A(op(0, 2))
    L1A = np.sqrt(gamma_r_per_us * b1) * A(op(1, 2))
    LdA = np.sqrt(gamma_r_per_us * bd) * A(op(3, 2))

    L0B = np.sqrt(gamma_r_per_us * b0) * B_(op(0, 2))
    L1B = np.sqrt(gamma_r_per_us * b1) * B_(op(1, 2))
    LdB = np.sqrt(gamma_r_per_us * bd) * B_(op(3, 2))

    return [L0A, L1A, LdA, L0B, L1B, LdB]


def arp_pulses(T_us, Omega_MHz, Delta_MHz, tau_frac):
    """
    Adiabatic rapid passage pulse shapes used in Module 2
    for the CZ gate.

    Returns two callables Omega(t), Delta(t) (rad/us).
    """
    tau = tau_frac * T_us
    a = np.exp(-((T_us / 4) / tau) ** 4)

    Omega0 = w(Omega_MHz)   # rad/us
    Delta0 = w(Delta_MHz)   # rad/us

    def Omega(t):
        if 0.0 <= t <= T_us:
            t0 = T_us / 4 if t < T_us / 2 else 3 * T_us / 4
            shape = (np.exp(-((t - t0) ** 4) / (tau ** 4)) - a) / (1.0 - a)
            return Omega0 * shape
        return 0.0

    def Delta(t):
        if 0.0 <= t <= T_us:
            return -Delta0 * np.cos(TWOPI * t / T_us)
        return 0.0

    return Omega, Delta


def make_H_twoatom(T_us, Omega_MHz, Delta_MHz, tau_frac, B_MHz):
    """
    Build time-dependent 2-atom Hamiltonian H(t) for the ARP CZ gate
    in the full 16-dim space (two 4-level atoms).
    """
    Omega, Delta = arp_pulses(T_us, Omega_MHz, Delta_MHz, tau_frac)
    Bshift = w(B_MHz)

    X01_A = A(Er1 + E1r)
    X01_B = B_(Er1 + E1r)
    PrA   = A(P_rr_single)
    PrB   = B_(P_rr_single)

    def H_of_t(t):
        return (
            0.5 * Omega(t) * (X01_A + X01_B)
            + Delta(t) * (PrA + PrB)
            + Bshift * P_rr_rr
        )

    return H_of_t


def embed_4x4_to_16(r2q):
    """
    Embed 4x4 2-qubit computational density matrix (|00>,|01>,|10>,|11>)
    into the full 16x16 two-atom space, in the upper-left block.
    """
    rho = np.zeros((16, 16), dtype=DT)
    rho[:4, :4] = r2q
    return rho


def extract_4x4_from_16(rho16):
    """
    Project full 16x16 two-atom density matrix onto computational subspace.
    """
    return rho16[:4, :4].astype(DT)

# =================== X / Z / CZ physical channels ===================

def make_X_channel(
    Omega0_MHz=1.0,
    sigma_us=0.20,
    gamma_r_per_us=1/540.0,
    steps=4000,
):
    """
    1-qubit X gate channel from your Module-2 Gaussian π-pulse.

    Returns:
        channel_X(rho2)  # maps 2x2 -> 2x2
    """
    gamma_r_inv_us = 1.0 / gamma_r_per_us

    ts, traj0, traj1, pulse_evolve_fn, Ht, Ls = simulate_pulse_return_2x2(
        Omega0_MHz=Omega0_MHz,
        sigma_us=sigma_us,
        t0_us=0.0,
        gamma_r_inv_us=gamma_r_inv_us,
        steps=steps,
    )

    def channel_X(rho2):
        # rho2 is a 2x2 density matrix on {|0>,|1>}
        return pulse_evolve_fn(rho2)

    return channel_X


def make_Z_channel(
    delta_MHz,
    T_det_us,
    gamma_r_per_us=1/540.0,
    steps=None,
):
    """
    1-qubit Z gate channel from our Module-2 detuning pulse.

    Returns:
        channel_Z(rho2)  # maps 2x2 -> 2x2
    """
    if steps is None:
        steps = max(1000, int(200 * T_det_us))

    Ls = lindblad_jumps(gamma_r_per_us)
    Ht = H_detuning_of_t(delta_MHz, T_det_us)

    def channel_Z(rho2):
        # 1) embed into 4-level space |0>,|1>,|r>,|d>
        rho4 = embed_2x2_to_4x4(rho2.astype(DT))

        # 2) evolve under H(t) + Ls
        tspan = (0.0, T_det_us)
        ts, traj = evolve_rho(tspan, rho4, Ht, Ls, steps=steps)

        # 3) project back onto computational subspace
        rho4_final = traj[-1]
        return extract_2x2_from_4x4(rho4_final)

    return channel_Z


def make_CZ_channel(
    two_atom_params_best,
    gamma_r_per_us=1/540.0,
    steps_per_us=300,
):
    """
    2-qubit CZ gate channel from our Module-2 two-atom ARP optimization.

    Args:
        two_atom_params_best: dict from your optimize_params_for_B(...)
            expected keys ~ "T", "Omega", "Delta", "B", "tau_frac"
        gamma_r_per_us: Rydberg decay rate
        steps_per_us: integration resolution;

    Returns:
        channel_CZ(rho4)   # maps 4x4 -> 4x4 on {|00>,|01>,|10>,|11>}
    """
    T_us      = float(two_atom_params_best["T"])
    Omega_MHz = float(two_atom_params_best["Omega"])
    Delta_MHz = float(two_atom_params_best["Delta"])
    B_MHz     = float(two_atom_params_best["B"])
    tau_frac  = float(two_atom_params_best["tau_frac"])

    # Time-dependent 2-atom Hamiltonian in 16-dim full space
    Ht = make_H_twoatom(T_us, Omega_MHz, Delta_MHz, tau_frac, B_MHz)

    # Two-atom Lindblad jumps (each atom decays r -> {0,1,d})
    Ls = lindblad_jumps_twoatom(gamma_r_per_us)

    steps = max(1000, int(steps_per_us * T_us))

    def channel_CZ(rho4):
        """
        rho4 is 4x4 density matrix on {|00>,|01>,|10>,|11>}.

        We:
          - embed into full 16x16 two-atom space,
          - evolve under H(t)+Lindblad,
          - project back to 4x4 computational subspace.
        """
        rho16_0 = embed_4x4_to_16(rho4.astype(DT))

        tspan = (0.0, T_us)
        ts, traj = evolve_rho(tspan, rho16_0, Ht, Ls, steps=steps)
        rho16_f = traj[-1]

        return extract_4x4_from_16(rho16_f)

    return channel_CZ

# === Module-2 calibrated parameters ===

# 1-qubit X π-pulse
sigma_pi_us   = 0.199471        # optimal σ for Ω0 = 1.0 MHz

# 1-qubit Z gate via detuning
delta_opt_MHz = 1.0             # detuning used in Module 2
T_Z_us        = 0.500156250     # optimized T* for Z(π)

# 2-qubit CZ ARP gate, best for B = 200 MHz
two_atom_params_best = {
    "T":       0.5336,          # gate duration (µs)
    "Omega":  17.24,            # Ω/2π in MHz
    "Delta":  22.99,            # Δ/2π in MHz
    "B":     200.0,             # blockade B/2π in MHz
    "tau_frac": 0.178,          # τ/T
}

from types import SimpleNamespace
from qutip import Qobj, basis, tensor
import numpy as np

# =================== Neutral-atom Processor using Module-2 gates ===================

class NAProcessor:
    """
    Neutral-atom style processor for Module 4 RB.

    Native ops:
      - ("rx", q, theta)
      - ("rz", q, phi)
      - ("cz", q0, q1)

    Noise model:
      - RX/RZ: Module-2 calibrated Xπ, Zπ physical channels
      - CZ    : Module-2 ARP CZ physical channel
    """
    def __init__(self,
                 num_qubits=2,
                 basis=("rx", "rz", "cz")):
        self.num_qubits = int(num_qubits)
        self.basis = tuple(map(str.lower, basis))
        self.ops = []

        # Neutral-atom parameters
        self.na_params = dict(
            gamma_r_lifetime_us=540.0,  # radiative lifetime
        )
        gamma_r_per_us = 1.0 / self.na_params["gamma_r_lifetime_us"]


        # --- 1Q physical channels ---
        self.X_chan = make_X_channel(
            Omega0_MHz=1.0,
            sigma_us=sigma_pi_us,
            gamma_r_per_us=gamma_r_per_us,
        )
        self.Z_chan = make_Z_channel(
            delta_MHz=delta_opt_MHz,
            T_det_us=T_Z_us,
            gamma_r_per_us=gamma_r_per_us,
        )

        # --- 2Q physical CZ channel ---
        self.CZ_chan = make_CZ_channel(
            two_atom_params_best,
            gamma_r_per_us=gamma_r_per_us,
        )

    # ---------- state prep ----------

    def generate_init_processor_state(self):
        """Return ρ₀ = |0...0><0...0| as a Qobj."""
        ket0 = basis(2, 0)
        psi = ket0
        for _ in range(self.num_qubits - 1):
            psi = tensor(psi, ket0)
        return psi * psi.dag()

    # ---------- circuit loading ----------

    def load_circuit(self, circ):
        """
        Convert a Qiskit QuantumCircuit into a list of native ops.
        Assumes the circuit has been transpiled to rx/rz/cz.
        """
        from qiskit import transpile

        circ_t = transpile(circ, basis_gates=list(self.basis))

        # Map Qiskit qubit objects -> integer indices
        qubit_indices = {qb: i for i, qb in enumerate(circ_t.qubits)}

        ops = []
        for inst, qargs, _ in circ_t.data:
            name = inst.name.lower()
            if name in ("barrier", "measure", "id", "delay"):
                continue

            if name == "rx":
                q = qubit_indices[qargs[0]]
                theta = float(inst.params[0])
                ops.append(("rx", q, theta))
            elif name == "rz":
                q = qubit_indices[qargs[0]]
                phi = float(inst.params[0])
                ops.append(("rz", q, phi))
            elif name == "cz":
                q0 = qubit_indices[qargs[0]]
                q1 = qubit_indices[qargs[1]]
                ops.append(("cz", q0, q1))
            else:
                raise ValueError(f"Non-native gate encountered: {name}")

        self.ops = ops
        return ops

    # ---------- physical gate application ----------

    def _apply_1q_gate_physical(self, rho_full: Qobj,
                            qubit: int,
                            axis: str,
                            angle: float) -> Qobj:
        """
        Apply a noisy 1Q gate on `qubit`:

        ρ  ──>  U_axis(angle) ρ U_axis(angle)†  ──>  physical noise channel

        where the noise channel (X_chan / Z_chan) comes from Module 2.
        """

        axis = axis.lower()
        if axis == "x":
           base_chan = self.X_chan
           def channel_2x2(rho2):
               # Ideal Rx(theta) in Qiskit convention: exp(-i θ X / 2)
               c = np.cos(angle / 2.0)
               s = np.sin(angle / 2.0)
               U = np.array([[c, -1j * s],
                          [-1j * s, c]], dtype=np.complex128)
               rho_rot = U @ rho2 @ U.conj().T
               return base_chan(rho_rot)

        elif axis == "z":
            base_chan = self.Z_chan
            def channel_2x2(rho2):
                # Ideal Rz(phi): exp(-i φ Z / 2)
                e_minus = np.exp(-0.5j * angle)
                e_plus  = np.exp(0.5j * angle)
                U = np.array([[e_minus, 0.0],
                          [0.0,      e_plus]], dtype=np.complex128)
                rho_rot = U @ rho2 @ U.conj().T
                return base_chan(rho_rot)

        else:
            raise ValueError(f"Unknown 1Q axis {axis}, expected 'x' or 'z'.")

        return apply_1q_channel_to_full_state(rho_full, qubit, channel_2x2)


    def _apply_2q_CZ_physical(self, rho_full: Qobj,
                              q0: int,
                              q1: int) -> Qobj:
        """
        Apply the physical 2Q CZ gate from Module-2.

        For simplicity we only support num_qubits == 2 and {q0,q1} = {0,1}.
        """
        if self.num_qubits != 2:
            raise NotImplementedError(
                "Physical CZ implemented only for 2-qubit NAProcessor."
            )
        if sorted((q0, q1)) != [0, 1]:
            raise NotImplementedError(
                "CZ only implemented for qubits (0,1) in this simple version."
            )

        R = rho_full.full().astype(np.complex128, copy=True)  # 4x4
        R_prime = self.CZ_chan(R)  # 4x4 -> 4x4
        return Qobj(R_prime, dims=rho_full.dims)

    # ---------- run & get final state ----------

    def run_state(self, init_state: Qobj):
        """
        Apply all stored operations to init_state and return
        SimpleNamespace(states=[init_state, final_rho]).
        """
        rho = init_state
        for op in self.ops:
            tag = op[0]
            if tag == "rx":
                _, q, theta = op
                rho = self._apply_1q_gate_physical(rho, q, axis="x", angle=theta)
            elif tag == "rz":
                _, q, phi = op
                rho = self._apply_1q_gate_physical(rho, q, axis="z", angle=phi)
            elif tag == "cz":
                _, q0, q1 = op
                rho = self._apply_2q_CZ_physical(rho, q0, q1)
            else:
                raise RuntimeError(f"Unknown op {op}")
        return SimpleNamespace(states=[init_state, rho])

    def get_final_circuit_state(self, result_or_state, renorm: bool = True) -> Qobj:
        """
        Given either the SimpleNamespace from run_state(.) or directly
        a Qobj density matrix, return the final state (optionally renormalized).
        """
        if isinstance(result_or_state, SimpleNamespace):
            rho = result_or_state.states[-1]
        else:
            rho = result_or_state

        if renorm:
            rho = rho / rho.tr()
        return rho

import uuid
import numpy as np

from qiskit.providers import BackendV2, JobV1, Options
from qiskit.providers.jobstatus import JobStatus
from qiskit.transpiler import Target, InstructionProperties
from qiskit.circuit.library import RXGate, RZGate, CZGate, Measure
from qiskit.result import Result
from qutip import Qobj


def apply_1q_channel_to_full_state(rho_full: Qobj,
                                   q: int,
                                   channel_2x2):
    """
    Apply a CPTP map E on qubit q of an n-qubit density matrix rho_full.
    E is given as a function channel_2x2(rho2) acting on 2x2 matrices.

    We use the same bit-order convention as the marginalization helper below:
      index i -> bits[b] = (i >> (n-1-b)) & 1,  b = 0..n-1
    so qubit 0 is the *leftmost* bit in the computational basis.
    """
    dims = rho_full.dims[0]
    n = len(dims)
    assert all(d == 2 for d in dims), "Only supports qubits."

    R = rho_full.full().astype(np.complex128, copy=True)
    R_out = np.zeros_like(R, dtype=np.complex128)

    def bits_from_index(i):
        # bits[b] = value (0/1) of qubit b, with b=0 the leftmost
        return [(i >> (n - 1 - b)) & 1 for b in range(n)]

    def index_from_bits(bits):
        # bits[b] as above -> integer index
        idx = 0
        for b in range(n):
            idx = (idx << 1) | bits[b]
        return idx

    rest = [b for b in range(n) if b != q]
    k_rest = len(rest)

    for alpha in range(2**k_rest):
        bits_alpha = [0] * n
        for j, b in enumerate(rest):
            # encode alpha MSB-first over rest
            bits_alpha[b] = (alpha >> (k_rest - 1 - j)) & 1

        for beta in range(2**k_rest):
            bits_beta = [0] * n
            # assign rest bits for "ket" index
            for j, b in enumerate(rest):
                bits_beta[b] = (beta >> (k_rest - 1 - j)) & 1

            # build 2x2 block on target qubit q
            block = np.zeros((2, 2), dtype=np.complex128)
            for x in (0, 1):
                bits_alpha[q] = x
                i_idx = index_from_bits(bits_alpha)
                for y in (0, 1):
                    bits_beta[q] = y
                    j_idx = index_from_bits(bits_beta)
                    block[x, y] = R[i_idx, j_idx]

            # apply physical 1Q channel
            block_prime = channel_2x2(block)

            # write back
            for x in (0, 1):
                bits_alpha[q] = x
                i_idx = index_from_bits(bits_alpha)
                for y in (0, 1):
                    bits_beta[q] = y
                    j_idx = index_from_bits(bits_beta)
                    R_out[i_idx, j_idx] = block_prime[x, y]

    return Qobj(R_out, dims=rho_full.dims)


# ---------- helpers for probabilities / marginals ----------

def _bitstrings(k: int):
    """Return all k-bit strings from '0...0' to '1...1'."""
    return [format(i, f"0{k}b") for i in range(2**k)]


def _marginal_probs_from_diag(diag: np.ndarray, n_full: int, keep_indices):
    """
    Sum probabilities over dropped qubits.

    Parameters
    ----------
    diag : np.ndarray
        Diagonal of the full density matrix (length 2**n_full).
    n_full : int
        Total number of qubits in the processor.
    keep_indices : iterable[int]
        Indices of qubits we keep (in the processor's numbering).

    Returns
    -------
    p_keep : np.ndarray
        Marginalized probabilities on the kept qubits.
    labels : list[str]
        Bitstring labels (MSB = smallest qubit index in keep_indices).
    """
    keep = tuple(sorted(int(i) for i in keep_indices))
    k = len(keep)
    if k == n_full:
        return diag.copy(), _bitstrings(k)

    out = np.zeros(2**k, dtype=float)
    for i in range(2**n_full):
        # bits[b] = value of qubit b (0/1), b=0 is leftmost (MSB)
        bits = [(i >> (n_full - 1 - b)) & 1 for b in range(n_full)]
        idx = 0
        for b in keep:
            idx = (idx << 1) | bits[b]
        out[idx] += float(diag[i])

    return out, _bitstrings(k)


# ---------- minimal synchronous Job wrapper ----------

class _NAJob(JobV1):
    """
    Minimal synchronous Job wrapper so Experiments can call job.result().
    """
    def __init__(self, backend, result):
        super().__init__(backend, str(uuid.uuid4()))
        self._result = result
        self._status = JobStatus.DONE

    def result(self, timeout=None):
        return self._result

    def status(self):
        return self._status

    def submit(self):
        pass

    def cancel(self):
        self._status = JobStatus.CANCELLED

    def done(self):
        return True


# ---------- BackendV2 wrapper ----------

class NAPulseBackend(BackendV2):
    """
    BackendV2 wrapper around a neutral-atom-style processor.

    The `processor` object must provide:
      - num_qubits : int
      - load_circuit(qiskit_circuit)
      - generate_init_processor_state() -> qutip.Qobj
      - run_state(rho0) -> object with .states[-1] = final rho
      - get_final_circuit_state(res, renorm=False) -> qutip.Qobj

    This backend:
      * expects circuits already transpiled to ('rx','rz','cz')
      * simulates them with the processor
      * marginalizes onto the active qubits for counts
      * returns a Job whose result() is a qiskit.result.Result suitable for RB.
    """
    def __init__(self, processor, basis=("rx", "rz", "cz"), shots=4000):
        super().__init__(name="na_pulse")
        self.processor = processor
        self._basis = tuple(basis)
        self.set_options(shots=int(shots))

        # Build a simple Target describing native operations
        n = processor.num_qubits
        tgt = Target(num_qubits=n)

        rx_props = {(q,): InstructionProperties() for q in range(n)}
        rz_props = {(q,): InstructionProperties() for q in range(n)}
        cz_props = {
            (i, j): InstructionProperties()
            for i in range(n)
            for j in range(i + 1, n)
        }
        meas_props = {(q,): InstructionProperties() for q in range(n)}

        tgt.add_instruction(RXGate(0.0), rx_props)
        tgt.add_instruction(RZGate(0.0), rz_props)
        if cz_props:
            tgt.add_instruction(CZGate(), cz_props)
        tgt.add_instruction(Measure(), meas_props)

        self._target = tgt

    # ---- BackendV2 abstract bits ----
    @classmethod
    def _default_options(cls):
        return Options(shots=4000)

    @property
    def max_circuits(self):
        return None

    @property
    def target(self):
        return self._target

    @property
    def num_qubits(self):
        return self.processor.num_qubits

    # ---- main run ----
    def run(self, circuits, **kwargs):
        """
        Simulate circuits and return a Job wrapping a qiskit Result.

        We:
          * use `shots` from kwargs or backend options,
          * for each circuit:
              - use the processor to get the final density matrix,
              - compute diagonal probabilities,
              - marginalize to only the active qubits,
              - sample shots from that distribution to form classical counts,
              - attach RB metadata (xval, physical_qubits) so analysis works.
        """
        if not isinstance(circuits, (list, tuple)):
            circuits = [circuits]

        shots = int(kwargs.get("shots", getattr(self.options, "shots", 4000)))

        results = []
        n_full = self.processor.num_qubits
        rng = np.random.default_rng()

        for tc in circuits:
            # ---- metadata for RB ----
            meta = dict(getattr(tc, "metadata", {}) or {})

            # xval / length for RB grouping
            if "xval" not in meta:
                L = meta.get("clifford_length", meta.get("length", None))
                if L is None:
                    try:
                        L = int(tc.depth())
                    except Exception:
                        L = None
                if L is not None:
                    meta["xval"] = L

            # physical_qubits for RB
            if "physical_qubits" not in meta:
                try:
                    phys = list(tc.metadata.get("physical_qubits"))
                except Exception:
                    phys = list(range(tc.num_qubits))
                meta["physical_qubits"] = phys

            # Active qubits (for marginalization order)
            try:
                active_idx = [tc.find_bit(q).index for q in tc.qubits]
            except Exception:
                active_idx = list(range(tc.num_qubits))

            # ---- simulate via processor ----
            self.processor.load_circuit(tc)
            rho0 = self.processor.generate_init_processor_state()
            sim_res = self.processor.run_state(rho0)

            rho = self.processor.get_final_circuit_state(sim_res, renorm=False)

            # Diagonal probabilities over full register
            diag = np.real_if_close(np.diag(rho.full()).ravel())
            diag = np.clip(diag, 0.0, 1.0)

            # Marginalize to active qubits: get distribution over bitstrings
            p_act, labels = _marginal_probs_from_diag(diag, n_full, active_idx)
            s = p_act.sum()
            if s > 0:
                p_act = p_act / s
            else:
                p_act = np.ones_like(p_act) / len(p_act)

            # Sample counts
            counts_vec = rng.multinomial(shots, p_act)
            counts = {
                labels[i]: int(c)
                for i, c in enumerate(counts_vec)
                if c > 0
            }

            results.append(
                {
                    "shots": shots,
                    "success": True,
                    "metadata": meta,
                    "header": {"metadata": meta},
                    "data": {"counts": counts},
                }
            )

        qiskit_res = Result.from_dict(
            {
                "backend_name": self.name,
                "backend_version": "0.0.1",
                "job_id": str(uuid.uuid4()),
                "qobj_id": "na",
                "success": True,
                "results": results,
            }
        )
        return _NAJob(self, qiskit_res)


# Instantiate a 2-qubit neutral-atom device + backend
proc = NAProcessor(num_qubits=2, basis=("rx", "rz", "cz"))
backend = NAPulseBackend(proc)

print("Backend ready:", backend.name, "| num_qubits =", backend.num_qubits)

import numpy as np
from qiskit.quantum_info import SparsePauliOp

h_field = 0.7

H_op = SparsePauliOp.from_list([
    ("ZZ", -1.0),
    ("XI", -h_field),
    ("IX", -h_field),
])

# Dense 4x4 matrix for exact calculations
H_matrix = H_op.to_matrix()

# Exact ground-state energy (for reference)
eigvals, eigvecs = np.linalg.eigh(H_matrix)
E_exact = float(np.min(eigvals))

print("H matrix:\n", H_matrix)
print("Exact ground-state energy E_exact =", E_exact)

from qiskit.circuit import QuantumCircuit

def make_ansatz(thetas):
    """
    2-qubit ansatz:

    |0,0> --Ry(θ0)
                     │
    |0,1> --Ry(θ1)--CZ--

    thetas: array-like of length 2
    """
    theta0, theta1 = float(thetas[0]), float(thetas[1])
    qc = QuantumCircuit(2)
    qc.ry(theta0, 0)
    qc.ry(theta1, 1)
    qc.cz(0, 1)
    return qc

from qiskit.quantum_info import Statevector

def energy_ideal_statevector(thetas):
    qc = make_ansatz(thetas)
    psi = Statevector.from_instruction(qc).data.reshape(-1, 1)  # 4x1 column
    E = np.real(np.conjugate(psi.T) @ H_matrix @ psi)[0, 0]
    return float(E)

# quick sanity check
test_thetas = np.array([0.3, 1.0])
print("Sanity: E_ideal(test) =", energy_ideal_statevector(test_thetas))

from qiskit_aer import AerSimulator

def _exp_from_counts_Z0Z1(counts):
    total = sum(counts.values())
    if total == 0:
        return 0.0

    exp = 0.0
    for bitstr, c in counts.items():
        # bitstr is like 'q1 q0' (q1 most significant, q0 least)
        i = int(bitstr, 2)
        b0 = (i >> 0) & 1  # qubit 0
        b1 = (i >> 1) & 1  # qubit 1
        z0 = 1.0 if b0 == 0 else -1.0
        z1 = 1.0 if b1 == 0 else -1.0
        exp += z0 * z1 * c
    return exp / total


def _exp_from_counts_Z0(counts):
    total = sum(counts.values())
    if total == 0:
        return 0.0

    exp = 0.0
    for bitstr, c in counts.items():
        i = int(bitstr, 2)
        b0 = (i >> 0) & 1
        z0 = 1.0 if b0 == 0 else -1.0
        exp += z0 * c
    return exp / total


def _exp_from_counts_Z1(counts):
    total = sum(counts.values())
    if total == 0:
        return 0.0

    exp = 0.0
    for bitstr, c in counts.items():
        i = int(bitstr, 2)
        b1 = (i >> 1) & 1
        z1 = 1.0 if b1 == 0 else -1.0
        exp += z1 * c
    return exp / total

def energy_from_backend(backend, thetas, shots=1024):
    """
    Estimate <H> on a given backend using shots.

    H = -Z0 Z1 - h (X0 + X1)
    """
    thetas = np.array(thetas, dtype=float)
    backend.set_options(shots=shots)

    # --------- <Z0 Z1> ---------
    qc_zz = make_ansatz(thetas)
    qc_zz.measure_all()
    job = backend.run(qc_zz)
    res = job.result()
    counts_zz = res.get_counts()
    exp_ZZ = _exp_from_counts_Z0Z1(counts_zz)

    # --------- <X0> via H on qubit 0 → Z0 ---------
    qc_x0 = make_ansatz(thetas)
    qc_x0.h(0)
    qc_x0.measure_all()
    job = backend.run(qc_x0)
    counts_x0 = job.result().get_counts()
    exp_X0 = _exp_from_counts_Z0(counts_x0)

    # --------- <X1> via H on qubit 1 → Z1 ---------
    qc_x1 = make_ansatz(thetas)
    qc_x1.h(1)
    qc_x1.measure_all()
    job = backend.run(qc_x1)
    counts_x1 = job.result().get_counts()
    exp_X1 = _exp_from_counts_Z1(counts_x1)

    # Combine into energy
    E = -exp_ZZ - h_field * (exp_X0 + exp_X1)
    return float(E)


ideal_backend = AerSimulator()

print("Sanity (ideal backend, few shots):",
      energy_from_backend(ideal_backend, test_thetas, shots=2048))
print("Sanity (statevector exact):       ",
      energy_ideal_statevector(test_thetas))

def simple_vqe(backend, num_iters=15, init_thetas=None,
               step=0.4, shots=1024, label=""):
    """
     Derivative-free optimizer:
    - Start from init_thetas (random if None)
    - Each iteration: evaluate energy, then try +/- step on each parameter
      and keep the best move.
    - Shrink step slightly each iteration.
    """
    if init_thetas is None:
        init_thetas = 2 * np.pi * np.random.rand(2)
    thetas = np.array(init_thetas, dtype=float)

    history = []
    for it in range(num_iters):
        E = energy_from_backend(backend, thetas, shots=shots)
        history.append(E)
        print(f"[{label}] iter {it:02d}: E = {E:.6f}, thetas = {thetas}")

        # Try local moves on each parameter
        for i in range(len(thetas)):
            best_E = E
            best_theta_i = thetas[i]
            for delta in (+step, -step):
                trial = thetas.copy()
                trial[i] += delta
                E_trial = energy_from_backend(backend, trial, shots=shots)
                if E_trial < best_E:
                    best_E = E_trial
                    best_theta_i = trial[i]
            # Accept improvement
            if best_E < E:
                E = best_E
                thetas[i] = best_theta_i

        # Shrink step slowly
        step *= 0.9

    return thetas, history

# 1) VQE on ideal Aer backend (almost noiseless, just shot noise)
print("=== VQE on ideal AerSimulator (qasm) ===")
thetas_ideal, hist_ideal = simple_vqe(
    ideal_backend,
    num_iters=15,
    shots=4096,
    label="ideal",
)

print("\nFinal ideal thetas:", thetas_ideal)
print("Final ideal energy (backend) =", hist_ideal[-1])
print("Exact ground-state energy    =", E_exact)

# 2) VQE on neutral-atom backend
print("\n=== VQE on neutral-atom backend ===")
thetas_na, hist_na = simple_vqe(
    backend,        # this is NAPulseBackend(proc)
    num_iters=8,
    shots=64,
    label="NA",
)

print("\nFinal NA thetas:", thetas_na)
print("Final NA energy (backend) =", hist_na[-1])
print("Exact ground-state energy =", E_exact)

import matplotlib.pyplot as plt

plt.figure()
plt.plot(hist_ideal, marker="o", label="Ideal backend")
plt.plot(hist_na, marker="s", label="Neutral-atom backend")
plt.axhline(E_exact, color="k", linestyle="--", label="Exact ground energy")
plt.xlabel("Iteration")
plt.ylabel("Estimated energy")
plt.legend()
plt.grid(True)
plt.show()

from IPython.display import Markdown, display

display(Markdown(r"""
## Module 5 – VQE with a Neutral-Atom Backend

### 1. Neutral-atom backend recap

In Modules 2–4 I built a neutral-atom simulator and wrapped it as a Qiskit backend.

* **Physical model.** The `NAProcessor` evolves an $n$-qubit density matrix using the same 4–level neutral-atom Hamiltonians and Lindblad operators as in Module 2 (ground states $\lvert 0\rangle, \lvert 1\rangle$, Rydberg level $\lvert r\rangle$, and loss state $\lvert d\rangle$).

* **Gate channels.** Each physical gate is implemented as a noisy channel:
  * $E_X$: Gaussian $\pi$-pulse X gate with decay,
  * $E_Z$: detuning-based Z phase gate,
  * $E_{\text{CZ}}$: two-atom ARP CZ gate.

  To apply a gate on one or two qubits, I extract the corresponding $2\times 2$ or $4\times 4$ block from the full $2^n\times 2^n$ density matrix, run it through the appropriate channel, and re-embed the updated block back into the full state.

* **Qiskit backend.** The `NAPulseBackend` class wraps this processor as a `BackendV2` object. Any Qiskit circuit made from `rx`, `rz`, and `cz` is transpiled to that gate set and executed with the physical channels rather than ideal unitaries.

In Module 4, 1Q and 2Q randomized benchmarking on this backend gave extremely small error-per-Clifford values (of order $10^{-10}$), indicating very high gate fidelity in this simulated device.

---

### 2. VQE problem and ansatz

For Module 5 I studied a simple 2–qubit Ising-like Hamiltonian
$H = -Z_0 Z_1 - h (X_0 + X_1)$ with $h = 0.7$.

I represented $H$ in Qiskit as a `SparsePauliOp` and diagonalized the corresponding $4\times 4$ matrix to obtain the exact ground-state energy
$E_\text{gs}^\text{exact} \approx -1.72$.

For the VQE ansatz I used a small 2–parameter circuit:
1. Apply $R_y(\theta_0)$ on qubit 0 and $R_y(\theta_1)$ on qubit 1.
2. Apply a CZ gate between qubits 0 and 1.

This defines a variational state $\lvert\psi(\boldsymbol{\theta})\rangle$ with $\boldsymbol{\theta} = (\theta_0,\theta_1)$.

To evaluate the energy for a given $\boldsymbol{\theta}$, I wrote a helper
`energy_from_backend(backend, thetas)` which:

* builds the ansatz circuit,
* measures each Pauli term in $H$ using standard basis-rotation and shot-based sampling,
* combines the terms to estimate $\langle H\rangle$.

I then implemented a simple coordinate-descent style optimizer `simple_vqe`. Starting from random angles, each iteration evaluates the current energy and tries small $\pm$ steps on each parameter, keeping the best move. I ran this routine on

1. an **ideal** `AerSimulator` (qasm), and
2. my **neutral-atom** `NAPulseBackend`.

---

### 3. Results

The figure produced by my code (energy vs iteration) compares three quantities:

* **Exact ground-state energy.** From diagonalizing $H$ I obtained
  $E_\text{gs}^\text{exact} \approx -1.72$.

* **VQE on the ideal backend (blue curve).**
  I ran 15 iterations with a few hundred shots per energy evaluation. The energy decreased from an initial value close to zero to
  $E_\text{ideal}^\text{final} \approx -1.37$,
  which is still above the exact ground-state energy. This is expected: the ansatz is very small and my optimizer is simple, so the algorithm finds a good but not perfect approximation to the ground state.

* **VQE on the neutral-atom backend (orange curve).**
  On the neutral-atom backend I ran 8 iterations with 64 shots per energy evaluation. The energy starts around $-0.53$ and then drops rapidly, eventually reaching
  $E_\text{NA}^\text{final} \approx -2.35$.
  This value lies *below* the exact ground-state energy. A true expectation value of $H$ cannot go below the ground-state energy, so this is a sign that the *estimated* VQE energy is biased by the combination of finite shots, realistic gate noise, and the way I measure each Pauli term separately and then recombine them.

---

### 4. Discussion and takeaways

This module connects the QCVV-style characterization from Modules 2–4 with an actual algorithm running on the same backend.

* **RB vs algorithm performance.**
  Randomized benchmarking told me that the simulated neutral-atom gates have extremely small EPC, essentially “almost ideal” at the level of random Clifford sequences. However, when those same gates are used inside VQE, the estimated energies can be noticeably distorted and even fall below the true ground-state energy. RB and VQE probe different aspects of the noise.

* **Noise can bias the cost function.**
  On the ideal backend, shot noise mostly adds small fluctuations around the true energy. On the neutral-atom backend, the combination of decoherence, leakage channels, and my measurement scheme can systematically bias the Monte Carlo estimates of $\langle H\rangle$. The optimizer then learns to exploit that bias, not just minimize the true physical energy.

* **Algorithmic limitations still matter.**
  Even on the ideal backend, my simple ansatz and coordinate-descent optimizer stop around $-1.37$, above the true minimum $-1.72$. So part of the error is purely algorithmic. The neutral-atom backend then adds another layer of noise and bias on top of that.

Overall, Module 5 shows that a physically motivated neutral-atom simulator can be used as a noisy Qiskit backend for algorithms like VQE, and that “good RB numbers” do not automatically guarantee accurate algorithmic output. The full picture requires looking at both gate-level metrics (EPC, fidelity) and end-to-end algorithm behaviour (here, how close VQE gets to the true ground-state energy).
"""))