# -*- coding: utf-8 -*-
"""softwaremodule3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1knpF6K4LVRGGCC3Adxv8nXVlV4pUc3j2
"""

!pip -q install qutip qutip-qip qiskit prettytable numpy matplotlib

# Commented out IPython magic to ensure Python compatibility.
# %%writefile gates_na.py
# import numpy as np
# from qutip import Qobj
# 
# # ---------------------------
# # helpers
# # ---------------------------
# def rot_x(theta):
#     """2x2 unitary exp(-i theta/2 X)."""
#     c = np.cos(theta/2.0)
#     s = np.sin(theta/2.0)
#     return np.array([[c, -1j*s], [-1j*s, c]], dtype=np.complex128)
# 
# def rot_z(phi):
#     """2x2 unitary exp(-i phi/2 Z)."""
#     e_m = np.exp(-1j*phi/2.0)
#     e_p = np.exp(+1j*phi/2.0)
#     return np.array([[e_m, 0.0], [0.0, e_p]], dtype=np.complex128)
# 
# def embed_1q_unitary(U2, q, n):
#     mats = []
#     for idx in range(n):
#         mats.append(U2 if idx == (n-1-q) else np.eye(2, dtype=np.complex128))
#     M = mats[0]
#     for k in range(1, n):
#         M = np.kron(M, mats[k])
#     return M
# 
# def apply_unitary_on_qubit(rho_qobj, U2, q, n):
#     """Return Qobj after applying 1-qubit unitary U2 on target q."""
#     U = embed_1q_unitary(U2, q, n)
#     R = rho_qobj.full()
#     R2 = U @ R @ U.conj().T
#     return Qobj(R2, dims=rho_qobj.dims)
# 
# def rx_gate_na(rho_qobj, theta, **_):
#     """
#     RX gate acting in the qubit manifold {|0>,|1>} only.
#     No leakage; fast and stable for Module-3 tests.
#     """
#     n = int(np.log2(rho_qobj.shape[0]))
#     U2 = rot_x(theta)
#     raise RuntimeError("rx_gate_na should be wrapped by the processor; call with target qubit")
# 
# def rz_gate_na(rho_qobj, phi, **_):
#     """
#     RZ gate acting in the qubit manifold {|0>,|1>} only.
#     """
#     n = int(np.log2(rho_qobj.shape[0]))
#     U2 = rot_z(phi)
#     raise RuntimeError("rz_gate_na should be wrapped by the processor; call with target qubit")
# 
# def cz_gate_na(rho_qobj, q0, q1, *, T_us=0.54, gamma_r_lifetime_us=540.0, **_):
#     """
#     Fast CZ channel on two targets (q0,q1):
#       - ideal CZ phase: diag(1,1,1,-1)
#       - leakage-ish loss only on |11> with survival s = exp(-T/gamma_r_lifetime)
#     """
#     n = int(np.log2(rho_qobj.shape[0]))
#     N = 1 << n
#     R = rho_qobj.full().astype(np.complex128, copy=True)
# 
#     k0 = (n-1-q0)  # Qiskit LSB ordering
#     k1 = (n-1-q1)
# 
#     def is11(idx): return ((idx >> k0) & 1) and ((idx >> k1) & 1)
# 
#     s = np.exp(-float(T_us) / float(gamma_r_lifetime_us))
#     amp  = np.ones(N, dtype=np.float64)
#     sign = np.ones(N, dtype=np.int8)
#     for i in range(N):
#         if is11(i):
#             amp[i] = np.sqrt(s)
#             sign[i] = -1
# 
#     R = (sign[:,None]*sign[None,:]) * (amp[:,None]*amp[None,:]) * R
#     return Qobj(R, dims=rho_qobj.dims)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile na_processor.py
# import numpy as np
# from types import SimpleNamespace
# from qutip import Qobj, basis, tensor
# from gates_na import cz_gate_na
# 
# # ---------- local helpers ----------
# def rot_x(theta):
#     c, s = np.cos(theta/2.0), np.sin(theta/2.0)
#     return np.array([[c, -1j*s], [-1j*s, c]], dtype=np.complex128)
# 
# def rot_z(phi):
#     e_m, e_p = np.exp(-1j*phi/2.0), np.exp(+1j*phi/2.0)
#     return np.array([[e_m, 0.0], [0.0, e_p]], dtype=np.complex128)
# 
# def embed_1q_unitary(U2, q, n):
#     mats = [U2 if i==(n-1-q) else np.eye(2, dtype=np.complex128) for i in range(n)]
#     U = mats[0]
#     for k in range(1, n):
#         U = np.kron(U, mats[k])
#     return U
# 
# def _qidx(circ, qb):
#     """Robust qubit index across Qiskit versions."""
#     if hasattr(circ, "find_bit"):             # Terra ≥ 0.45
#         return int(circ.find_bit(qb).index)
#     if hasattr(qb, "index"):                  # some versions expose qb.index
#         return int(qb.index)
#     return int(circ.qubits.index(qb))         # fallback
# 
# # ---------- processor ----------
# class NAProcessor:
#     def __init__(self, num_qubits=2, basis=("rx","rz","cz")):
#         self.num_qubits = int(num_qubits)
#         self.basis = tuple(map(str.lower, basis))
#         self.ops = []
#         self.na_params = dict(T_us=0.54, gamma_r_lifetime_us=540.0)
# 
#     # Q1
#     def generate_init_processor_state(self):
#         ket0 = basis(2, 0)
#         psi = ket0
#         for _ in range(self.num_qubits-1):
#             psi = tensor(psi, ket0)
#         return psi * psi.dag()
# 
#     # Q2
#     def load_circuit(self, circ):
#         try:
#             from qiskit import transpile
#             circ = transpile(circ, basis_gates=list(self.basis))
#         except Exception:
#             pass
#         ops = []
#         for inst, qargs, _ in circ.data:
#             name = inst.name.lower()
#             if name in ("barrier", "measure", "id", "delay"):
#                 continue
#             if name == "rx":
#                 q = _qidx(circ, qargs[0]); theta = float(inst.params[0])
#                 ops.append(("rx", q, theta))
#             elif name == "rz":
#                 q = _qidx(circ, qargs[0]); phi = float(inst.params[0])
#                 ops.append(("rz", q, phi))
#             elif name == "cz":
#                 q0 = _qidx(circ, qargs[0]); q1 = _qidx(circ, qargs[1])
#                 ops.append(("cz", q0, q1))
#             else:
#                 raise ValueError(f"Non-native gate encountered: {name}")
#         self.ops = ops
#         return ops
# 
#     # Q3
#     def run_state(self, init_state: Qobj):
#         rho = init_state
#         n = self.num_qubits
#         for op in self.ops:
#             tag = op[0]
#             if tag == "rx":
#                 _, q, theta = op
#                 U = embed_1q_unitary(rot_x(theta), q, n)
#                 rho = Qobj(U @ rho.full() @ U.conj().T, dims=rho.dims)
#             elif tag == "rz":
#                 _, q, phi = op
#                 U = embed_1q_unitary(rot_z(phi), q, n)
#                 rho = Qobj(U @ rho.full() @ U.conj().T, dims=rho.dims)
#             elif tag == "cz":
#                 _, q0, q1 = op
#                 rho = cz_gate_na(rho, q0, q1, **self.na_params)
#             else:
#                 raise RuntimeError(f"Unknown op {op}")
#         return SimpleNamespace(states=[init_state, rho])
# 
#     # Q4
#     def get_final_circuit_state(self, result_or_state, renorm: bool = True) -> Qobj:
#         rho = result_or_state if isinstance(result_or_state, Qobj) else result_or_state.states[-1]
#         if renorm:
#             tr = float(rho.tr().real)
#             if tr > 0:
#                 rho = rho / tr
#         return rho
#

import importlib, na_processor
importlib.reload(na_processor)
from na_processor import NAProcessor

from qiskit import QuantumCircuit
proc = NAProcessor(2, basis=("rx","rz","cz"))
qc = QuantumCircuit(2); qc.h(0); qc.cx(0,1)
proc.load_circuit(qc)
rho0 = proc.generate_init_processor_state()
res  = proc.run_state(rho0)
print("trace =", float(res.states[-1].tr().real))

import numpy as np
import matplotlib.pyplot as plt
from prettytable import PrettyTable
from qiskit import QuantumCircuit, transpile
from qiskit.quantum_info import Statevector
from qutip import Qobj
from na_processor import NAProcessor

# ---------- helpers ----------
def ideal_state_from_circuit(circ: QuantumCircuit) -> np.ndarray:
    sv = Statevector.from_instruction(circ)
    return np.asarray(sv.data, dtype=np.complex128)

def rho_from_na(proc: NAProcessor, circ: QuantumCircuit, *, renorm: bool = True) -> Qobj:
    proc.load_circuit(transpile(circ, basis_gates=list(proc.basis)))
    rho0 = proc.generate_init_processor_state()
    res  = proc.run_state(rho0)
    rhoq = proc.get_final_circuit_state(res, renorm=renorm)
    return rhoq

def pure_state_fidelity(rho, psi: np.ndarray) -> float:
    R = rho.full() if hasattr(rho, "full") else np.asarray(rho, dtype=np.complex128)
    v = np.asarray(psi, dtype=np.complex128).reshape(-1,1)
    return float(np.real((v.conj().T @ R @ v)[0,0]))

def probs_from_rho(rho: Qobj) -> np.ndarray:
    p = np.real(np.diag(rho.full()))
    p = np.clip(p, 0.0, None)
    s = p.sum()
    return (p/s) if s > 0 else p

def probs_from_state(psi: np.ndarray) -> np.ndarray:
    p = np.abs(psi)**2
    return p / p.sum()

def tvd(p, q):  # total variation distance
    return 0.5 * float(np.abs(np.asarray(p)-np.asarray(q)).sum())

def rmse(p, q):
    return float(np.sqrt(np.mean((np.asarray(p)-np.asarray(q))**2)))

def show_bar_compare(p_id, p_na, title="Counts comparison"):
    x = np.arange(len(p_id))
    plt.figure(figsize=(6,3))
    plt.bar(x-0.2, p_id, width=0.4, label="ideal")
    plt.bar(x+0.2, p_na, width=0.4, label="NA")
    plt.xlabel("bitstring (decimal)")
    plt.ylabel("probability")
    plt.title(title); plt.legend(); plt.tight_layout(); plt.show()

# ---------- NA parameters (leakage only in CZ) ----------
default_na = dict(
    T_us=0.54,                 # affects CZ survival s=exp(-T/gamma)
    gamma_r_lifetime_us=540.0, # longer lifetime → less loss
)

# ---------- test circuits ----------
tests = []

# (1) 1q Rx(pi/2)
c = QuantumCircuit(1); c.rx(np.pi/2, 0)
tests.append(("1q Rx(pi/2)", c))

# (2) 1q Rz(pi/2) Rx(pi/2)
c = QuantumCircuit(1); c.rz(np.pi/2, 0); c.rx(np.pi/2, 0)
tests.append(("1q Rz Rx", c))

# (3) 2q Bell: H(0); CX(0,1)
c = QuantumCircuit(2); c.h(0); c.cx(0,1)
tests.append(("2q Bell (H,CX)", c))

# (4) 2q |11> -> CZ
c = QuantumCircuit(2); c.x(0); c.x(1); c.cz(0,1)
tests.append(("2q |11> -> CZ", c))

# (5) 2q random native + CZ
rng = np.random.default_rng(7)
c = QuantumCircuit(2)
for _ in range(4):
    q = int(rng.integers(0,2))
    if rng.random() < 0.6:
        c.rx(float(rng.uniform(-np.pi, np.pi)), q)
    else:
        c.rz(float(rng.uniform(-np.pi, np.pi)), q)
c.cz(0,1)
tests.append(("2q random native + CZ", c))

# ---------- run tests ----------
tbl = PrettyTable(["test", "nq", "trace(NA)", "F(state|renorm)", "TVD", "RMSE"])
for name, circ in tests:
    nq = circ.num_qubits

    proc = NAProcessor(nq, basis=("rx","rz","cz"))
    proc.na_params = default_na.copy()
    rho_na_noren  = rho_from_na(proc, circ, renorm=False)
    rho_na_renorm = rho_from_na(proc, circ, renorm=True)

    psi_id = ideal_state_from_circuit(circ)

    tr  = float(rho_na_noren.tr().real)
    Fid = pure_state_fidelity(rho_na_renorm, psi_id)

    p_id = probs_from_state(psi_id)
    p_na = probs_from_rho(rho_na_renorm)
    Tvd  = tvd(p_id, p_na)
    Rmse = rmse(p_id, p_na)

    tbl.add_row([name, nq, f"{tr:.6f}", f"{Fid:.6f}", f"{Tvd:.4f}", f"{Rmse:.4f}"])

print(tbl)

# ---------- show two distributions ----------
# Bell (should be ~[.5, 0, 0, .5] both ideal and NA)
name, circ = tests[2]
proc = NAProcessor(2, basis=("rx","rz","cz")); proc.na_params = default_na.copy()
rho_na = rho_from_na(proc, circ, renorm=True)
p_id   = probs_from_state(ideal_state_from_circuit(circ))
p_na   = probs_from_rho(rho_na)
show_bar_compare(p_id, p_na, title="Bell: ideal vs NA (probabilities)")

# CZ on |11> with extra loss to visualize leakage
name, circ = tests[3]
proc = NAProcessor(2, basis=("rx","rz","cz"))
lossy = default_na.copy(); lossy.update(dict(T_us=1.0, gamma_r_lifetime_us=100.0))
proc.na_params = lossy
rho_na = rho_from_na(proc, circ, renorm=True)
p_id   = probs_from_state(ideal_state_from_circuit(circ))
p_na   = probs_from_rho(rho_na)
show_bar_compare(p_id, p_na, title="|11> -> CZ: ideal vs NA (probabilities)")